### ISSUE TITLE
Implement efferent- and afferent-coupling for classes.

### ISSUE THREAD

**Issue by manuelpichler** [pdepend/pdepend#10]

**Comment by kylekatarnls** [comment]
Afferent couplings (Ca): The number of classes in other packages that depend upon classes within the package is an indicator of the package's responsibility. Afferent couplings signal inward.

Efferent couplings (Ce): The number of classes in other packages that the classes in a package depend upon is an indicator of the package's dependence on externalities. Efferent couplings signal outward.

**Comment by ravage84** [comment]
I haven't seen requests for this. Plus I guess it's rather "nice to have".

Let's close this until gets actually requested.
