### ISSUE TITLE
Parsing invalid PHP files should abort further execution

### ISSUE THREAD

**Issue by magicsunday** [pdepend/pdepend#108]
Parsing of an invalid PHP file, should stop the further execution of pdepend. The exit code should be set to an error code to prevent following task (for example when using automatic phing builds) from execution.

For example the following parser error:

    The following error occured:
    Unexpected token: ), line: 10, col: 3, file: /var/www/file.php.

**Comment by manuelpichler** [comment]
An abort would be to anoying for most command line users. Maybe a different exit code would be fine.
