### ISSUE TITLE
Unexpected token: case, line: 5 col: 8

### ISSUE THREAD

**Issue by rsumibcay** [pdepend/pdepend#109]
Ubuntu 10.04.4 LTS

1. Create a folder named test
2. Put the file test.php in the test folder with this content:

<?php
switch($current_section) {
	case "menu": ?>
		<?php break; ?>
	<?php case "freetaco": ?>
		<?php break; ?>
	<?php case "beachclub": ?>
		<?php break; ?>
	<?php case "fundraisers": ?>
		<?php break; ?>
	<?php default: ?>
<?php } ?>

3. %  pdepend --jdepend-xml=jdepend.xml test

PHP_Depend 1.1.0 by Manuel Pichler

Parsing source files:
.                                                                1

Executing Dependency-Analyzer:
.     0

Generating pdepend log files, this may take a moment.

The following error occured:
Unexpected token: case, line: 5, col: 8,

**Comment by manuelpichler** [comment]
Works with PDepend 2.x

```
manuel@Samweis pdepend.git $ src/bin/pdepend --jdepend-xml=/tmp/jdp.xml /tmp/switch.php
PDepend 2.1.0

Parsing source files:
.                                                                1

Calculating Dependency metrics:
.     0

Generating pdepend log files, this may take a moment.

Time: 0:00:00; Memory: 6.00Mb
manuel@Samweis pdepend.git $ 

```
