### ISSUE TITLE
pdepend doesn't work with asp-style tags

### ISSUE THREAD

**Issue by pkordylewski** [pdepend/pdepend#120]
Hey,

when trying to run pdepend on a php-file with asp-style tags the process just consumes all available memory until it runs into the memory limitation. Nothing else happens.

I have the following test file:

```php
<% if (true):%>
<%=foo::bar();%>
<% endif;%>
```

I'm running pdepend 1.1.0 on a PHP 5.3 installation:

```
pdepend --version
PHP_Depend 1.1.0 by Manuel Pichler
```

```
# pdepend --summary-xml=pdepend-tmp.xml pdepend-test.php
```

Cheers,
Patryk

**Comment by manuelpichler** [comment]
Since alternative tags will be deprecated in PHP 7, I think I can close this ticket
