### ISSUE TITLE
The added support for Trait does not check which version of php is used

### ISSUE THREAD

**Issue by sylvainv** [pdepend/pdepend#123]
I am using a code that requires php 5.3 and cannot run on php 5.4. We have classes named Trait, it is a reserved word in php 5.4. But everything is fine since we run our code on php 5.3.x. 

The problem comes when we are analyzing our code using pdepend, it adds support for php 5.4 traits without checking whether php 5.4 is indeed in use.

Could you please add conditional support for "trait" ?

**Comment by manuelpichler** [comment]
While rethinking this issue, it's one of PDepend's major benefits that you parse code for older or newer php versions, independent from the installed php binary.
