### ISSUE TITLE
Windows+Composer install fails due to "path too long"

### ISSUE THREAD

**Issue by ashnazg** [pdepend/pdepend#129]
A handfull of the test files with long class names will cause the ZipArchive::extractTo() method to fail, due to the Windows zip file reader saying "Path too long".

This seems to be due to the combination of the long filenames and pathing, on top of the long zip filename being set by either Composer or Github on the download step (I cannot tell which it is), e.g. "6fcfb7666c95f341b42f02c94a47b3a51ed484e0.zip".

The resulting total paths look like this example:  
C:\Users\cburgess\AppData\Local\Composer\files\pdepend\pdepend\6fcfb7666c95f341b42f02c94a47b3a51ed484e0\pdepend-pdepend-6fcfb76\src\test\resources\files\Code\ASTMemberPrimaryPrefix\testGraphDereferencedArrayFromStaticMethodCallAndMultipleMethodInvocations.php

It is simply pdepend-1.1.1 that my composer install step is trying to download and install, but the unzip step just can't succeed because of the some of the paths that Windows cannot unzip successfully ("path too long").

I realize it's probably not feasible for you to shorten your class names and path structure.  However, no amount of searches I've done leads to anything close to mentioning this issue, so I wanted to make a record of it that people will be able to find.

**Comment by gamicklisafisher** [comment]
https://github.com/aspnet/dnx/pull/810

**Comment by gamicklisafisher** [comment]
For deletion or handling of long name i check that "Long Path Tool" software should be try, many articles refer this for such solutions.

**Comment by ArminVieweg** [comment]
I've found a nice workarround, using 7-zip on windows to extract archives with "too long paths". Here you find the gist: https://gist.github.com/ArminVieweg/46ce21d9564586eb53b6
