### ISSUE TITLE
Proposal for a new filter setting

### ISSUE THREAD

**Issue by schmittjoh** [pdepend/pdepend#130]
Currently, pdepend supports excluding certain directories via the `excluded_dirs` option that can be passed. For usage on scrutinizer-ci.com, I'd like to contribute a new filter settings which is a bit more flexible:

---

```
filter:
    paths: [dir1/*, dir2/*]
    excluded_paths: [excluded_dir1/*, excluded_dir2/*]
```

All paths are defined relative to your root folder, and are checked in this order:
1. A file must match at least one path defined in the paths setting. If the paths setting is empty, this will be treated like if it would contain a single path *; that is it would always match.
2. A file must not match a single path defined in the excluded_paths setting.

---

Would you be interested in a patch for this?

**Comment by kylekatarnls** [comment]
I close this but if you're still needing this, feel free to propose a pull-request.
