### ISSUE TITLE
Endless inheritance hierarchy

### ISSUE THREAD

**Issue by sebastien-barthelemy** [pdepend/pdepend#159]
Hello,

I think it's not the first time you have this bug reported, but i didn't found it in issues.
On a simple phpunit test (TestFile extend AbstractBase, AbstractBase extend WebTestCase), i got a message : is part of an endless inheritance hierarchy.

Message is in a sample trace : 
#0 /usr/share/php/PHP/Depend/Code/AbstractClassOrInterface.php(103): PHP_Depend_Code_Exceptions_RecursiveInheritanceException->__construct(Object(PHP_Depend_Code_Class))
#1 /usr/share/php/PHP/Depend/Code/AbstractClassOrInterface.php(130): PHP_Depend_Code_AbstractClassOrInterface->getParentClass()
#2 /usr/share/php/PHP/Depend/Code/AbstractClassOrInterface.php(176): PHP_Depend_Code_AbstractClassOrInterface->getParentClasses()
#3 /usr/share/php/PHP/Depend/Metrics/ClassLevel/Analyzer.php(208): PHP_Depend_Code_AbstractClassOrInterface->getInterfaces()
#4 /usr/share/php/PHP/Depend/Code/Class.php(212): PHP_Depend_Metrics_ClassLevel_Analyzer->visitClass(Object(PHP_Depend_Code_Class))
#5 /usr/share/php/PHP/Depend/Visitor/AbstractVisitor.php(226): PHP_Depend_Code_Class->accept(Object(PHP_Depend_Metrics_ClassLevel_Analyzer))
#6 /usr/share/php/PHP/Depend/Code/Package.php(338): PHP_Depend_Visitor_AbstractVisitor->visitPackage(Object(PHP_Depend_Code_Package))
#7 /usr/share/php/PHP/Depend/Metrics/ClassLevel/Analyzer.php(142): PHP_Depend_Code_Package->accept(Object(PHP_Depend_Metrics_ClassLevel_Analyzer))
#8 /usr/share/php/PHP/Depend.php(593): PHP_Depend_Metrics_ClassLevel_Analyzer->analyze(Object(PHP_Depend_Code_NodeIterator))
#9 /usr/share/php/PHP/Depend.php(314): PHP_Depend->performAnalyzeProcess()
#10 /usr/share/php/PHP/PMD/Parser.php(128): PHP_Depend->analyze()
#11 /usr/share/php/PHP/PMD.php(203): PHP_PMD_Parser->parse(Object(PHP_PMD_Report))
#12 /usr/share/php/PHP/PMD/TextUI/Command.php(130): PHP_PMD->processFiles('...', '...', Array, Object(PHP_PMD_RuleSetFactory))
#13 /usr/share/php/PHP/PMD/TextUI/Command.php(154): PHP_PMD_TextUI_Command->run(Object(PHP_PMD_TextUI_CommandLineOptions), Object(PHP_PMD_RuleSetFactory))
#14 /usr/bin/phpmd(48): PHP_PMD_TextUI_Command::main(Array)
#15 {main}Type xxx\BaseTestCase is part of an endless inheritance hierarchy.

Do you have any idea on how i can handle this ?

Thanks,

**Comment by mikepmtl** [comment]
Having the same issue:
phpmd-ci:
    [phpmd] Type Fuel\Core\Asset is part of an endless inheritance hierarchy.
    [phpmd] Result: 1

Just stops and will not continue to output.

**Comment by manuelpichler** [comment]
I will close this issue, because there are no other reports about this problem within the last 12 months

**Comment by sherifadel-msft** [comment]
Same here:
 [exec] Critical error: 
     [exec] =============== 
     [exec] Type Symfony\Component\VarDumper\Tests\Fixtures\NotLoadableClass is part of an endless inheritance hierarchy.
     [exec] Result: 2
