### ISSUE TITLE
Feature request: note functions which throw undocumented exceptions

### ISSUE THREAD

**Issue by alberto56** [pdepend/pdepend#168]
As I described on http://stackoverflow.com/questions/24399070, I would find it useful to be notified when a function throws an exception, but it is not documented as such. In complex code, some functions should not throw exceptions, but perhaps they call a function which calls a function which throws an exception. Feature request: pdepend might give a list of functions which throw exceptions (because they directly or indirectly call functions which throw exceptions) but for which there is no @throws element in the documentation.

**Comment by ravage84** [comment]
I don't think PHP Depend is the right tool for that.

First of all your IDE, like  PhpStorm, can help you with that.

Also, there are tools like [PHPCS](https://github.com/squizlabs/PHP_CodeSniffer) that already provide this very requested functionality.

Closing now.
