### ISSUE TITLE
Pdepend fatal error on jenkins and sonar build

### ISSUE THREAD

**Issue by zied-ellouze** [pdepend/pdepend#184]
I got the following error on pdepend When i build a job by jenkins and sonar:
17:37:10.410 INFO  - PHP_Depend 1.1.4 by Manuel Pichler
17:37:10.411 INFO  - 
17:37:10.416 INFO  - Parsing source files:
17:37:11.348 DEBUG - Updating semaphore batch-org.drupal.d7
17:37:13.626 INFO  - PHP Fatal error:  Call to undefined method PHP_Depend_Code_ASTLiteral::setSourceFile() in /usr/share/pear/PHP/Depend/Code/File.php on line 374
17:37:13.626 INFO  - PHP Stack trace:
17:37:13.626 INFO  - PHP   1. {main}() /usr/bin/pdepend:0
17:37:13.626 INFO  - PHP   2. PHP_Depend_TextUI_Command::main() /usr/bin/pdepend:78
17:37:13.626 INFO  - ......................
17:37:13.627 INFO  - PHP   3. PHP_Depend_TextUI_Command->run() /usr/share/pear/PHP/Depend/TextUI/Command.php:701
17:37:13.627 INFO  - Fatal error: Call to undefined method PHP_Depend_Code_ASTLiteral::setSourceFile() in /usr/share/pear/PHP/Depend/Code/File.php on line 374
17:37:13.627 INFO  - 
17:37:13.627 INFO  - PHP   4. PHP_Depend_TextUI_Runner->run() /usr/share/pear/PHP/Depend/TextUI/Command.php:207
17:37:13.627 INFO  - Call Stack:
17:37:13.627 INFO  - PHP   5. PHP_Depend->analyze() /usr/share/pear/PHP/Depend/TextUI/Runner.php:331
17:37:13.627 INFO  - PHP   6. PHP_Depend->performParseProcess() /usr/share/pear/PHP/Depend.php:306
17:37:13.627 INFO  - PHP   7. PHP_Depend_Parser->parse() /usr/share/pear/PHP/Depend.php:560
17:37:13.627 INFO  -     0.0002     640648   1. {main}() /usr/bin/pdepend:0
17:37:13.627 INFO  -     0.0011     858880   2. PHP_Depend_TextUI_Command::main() /usr/bin/pdepend:78
17:37:13.627 INFO  -     0.0012     859656   3. PHP_Depend_TextUI_Command->run() /usr/share/pear/PHP/Depend/TextUI/Command.php:701
17:37:13.627 INFO  - PHP   8. PHP_Depend_Util_Cache_Driver_File->restore() /usr/share/pear/PHP/Depend/Parser.php:319
17:37:13.627 INFO  -     0.0052    1188704   4. PHP_Depend_TextUI_Runner->run() /usr/share/pear/PHP/Depend/TextUI/Command.php:207
17:37:13.627 INFO  - PHP   9. PHP_Depend_Util_Cache_Driver_File->restoreFile() /usr/share/pear/PHP/Depend/Util/Cache/Driver/File.php:193
17:37:13.627 INFO  -     0.0077    1736016   5. PHP_Depend->analyze() /usr/share/pear/PHP/Depend/TextUI/Runner.php:331
17:37:13.627 INFO  - PHP  10. unserialize() /usr/share/pear/PHP/Depend/Util/Cache/Driver/File.php:210
17:37:13.627 INFO  -     0.0096    2590144   6. PHP_Depend->performParseProcess() /usr/share/pear/PHP/Depend.php:306
17:37:13.627 INFO  - PHP  11. PHP_Depend_Code_File->__wakeup() /usr/share/pear/PHP/Depend/Util/Cache/Driver/File.php:210
17:37:13.627 INFO  -     3.2162   19012664   7. PHP_Depend_Parser->parse() /usr/share/pear/PHP/Depend.php:560
17:37:13.627 INFO  -     3.2164   19012848   8. PHP_Depend_Util_Cache_Driver_File->restore() /usr/share/pear/PHP/Depend/Parser.php:319
17:37:13.627 INFO  -     3.2165   19012968   9. PHP_Depend_Util_Cache_Driver_File->restoreFile() /usr/share/pear/PHP/Depend/Util/Cache/Driver/File.php:193
17:37:13.627 INFO  -     3.2165   19087752  10. unserialize() /usr/share/pear/PHP/Depend/Util/Cache/Driver/File.php:210
17:37:13.627 INFO  -     3.2205   19732712  11. PHP_Depend_Code_File->__wakeup() /usr/share/pear/PHP/Depend/Util/Cache/Driver/File.php:210
17:37:13.628 INFO  - 
17:37:13.646 DEBUG - Release semaphore on project : org.sonar.api.resources.Project@7b5e7126[id=11344,key=org.drupal.d7,qualifier=TRK], with key batch-org.drupal.d7
17:37:13.674 DEBUG - To prevent a memory leak, the JDBC Driver [com.mysql.jdbc.Driver] has been forcibly deregistered
17:37:13.675 DEBUG - Delete temporary directory: /tmp/sonar-batch91056788736407091153109583863322
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 1:18.073s
Final Memory: 12M/432M
INFO: ------------------------------------------------------------------------
ERROR: Error during Sonar runner execution
ERROR: Unable to execute Sonar
ERROR: Caused by: PHP Depend execution failed with returned code '255'. Please check the documentation of PHP Depend to know more about this failure.
ERROR: 
ERROR: To see the full stack trace of the errors, re-run SonarQube Runner with the -e switch.
ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.
Build step 'Invoke Standalone Sonar Analysis' marked build as failure
Finished: FAILURE

**Comment by manuelpichler** [comment]
PDepend 1.x is out dated and not maintained anymore.
