### ISSUE TITLE
question: npath, return, and else block

### ISSUE THREAD

**Issue by yoosefi** [pdepend/pdepend#188]
I was wondering if someone could explain to me why `foo()` here has npath of 4, and `bar()` has npath of 3, even though `return` implies `else`. It seems to me that continuations such as `return`, `break`, `continue`, and `throw` should implicitly mark sibling code as `else`.
```
<?
// npath 4
function foo($x) {
    if (!$x) {
        return false;
    }
    foreach ($x as $y) {
        echo $y;
    }
}

// npath 3
function bar($x) {
    if (!$x) {
        return false;
    }
    else {
        foreach ($x as $y) {
            echo $y;
        }
    }
}
```

**Comment by manuelpichler** [comment]
@yoosefi a ```return``` is path in the npath metric and so the npath complexity of ```foo()``` is simplified explained the sum of ```if<npath>``` + ```return<npath>``` and the product of (```if<npath>``` + ```return<npath>```) * ```foreach<npath>```, while ```bar()``` is just the sum of ```if<npath>``` + ```foreach<npath>``` and so these numbers are correct.
