### ISSUE TITLE
Potential Debug output

### ISSUE THREAD

**Issue by KingCrunch** [pdepend/pdepend#191]
I can see several (houndred) lines like

```
string(96) "/var/lib/jenkins/jobs/my-project/workspace/build/api/namespaces/Foo.Bar.BazNamespace.Classname.html"
```

It looks like it's a remaining `var_dump()` :wink: I use `pdepend-2.0.6.phar`

**Comment by manuelpichler** [comment]
There are never *.html files in PDepend, so I think that was debug output from something different

**Comment by KingCrunch** [comment]
@manuelpichler In that project we don't have any html file neither, but I cannot reproduce it anymore ...
