### ISSUE TITLE
UTF-8 Problems

### ISSUE THREAD

**Issue by Eternal-Infinity** [pdepend/pdepend#195]
Hi there,

I am pretty new to pdepend, but I haven't found any open issue related to this.

The company I work in is trying to make PDepend run in Jenkins.
After the first run we got the following output:
> [...]
> [exec] Warning: DOMElement::setAttribute(): string is not in UTF-8 in phar://PATH/pdepend.phar/src/main/php/PDepend/Report/Jdepend/Xml.php on line 231
> [exec] 
> [exec] Warning: DOMDocument::save(): output conversion failed due to conv error, bytes 0xFC 0x63 0x6B 0x74 in phar:/PATH/pdepend.phar/src/main/php/PDepend/Report/Jdepend/Xml.php on line 213
> [...]

Is this a problem with PDepend or is this a problem on our side?
As far as I understand, the problem is that the functions above get a string which contains characters that are non-UFT-8 like Umlauts (yes, our software is german and contains Umlauts :neutral_face:).
In a post on php.net I read:
>In case you append text nodes with special characters (e. g. Umlaut) to your XML document you should therefore use utf8_encode() with your text to convert it into UTF-8 before you append the text to the document. Otherwise you will get an error message like "output conversion failed due to conv error" at the save() command.

(http://php.net/manual/de/domdocument.save.php#67952)

These are only warnings, we still get a PDepend output, so it seems to be nothing serious.....MAYBE... :wink:

**Comment by Eternal-Infinity** [comment]
Found out, that it is not only a problem of umlauts, other special characters could be problematic too.
In PHPDOX there was a similar problem, the problems there were cause by the following special characters in our application:

• (\u2022)
€ (\u20AC)

**Comment by manuelpichler** [comment]
Duplicate with #143
