### ISSUE TITLE
Support ... operator in function call

### ISSUE THREAD

**Issue by manuelpichler** [pdepend/pdepend#204]
PDepend doesn't support the PHP 5.6 operator in function calls:

``` php
function foo($a, $b) {
} 

foo(...[1, 2]);
```

**Comment by StanAngeloff** [comment]
Is it possible to at least suppress parsing of the splat operator so files containing it don't cause _Unexpected token_ errors? It's an ugly hack, but at least it would allow the file to be analysed.

**Comment by Schodemeiss** [comment]
I'm suffering from this too. @StanAngeloff Did you have any luck finding a way of surpressing it for the time being?

**Comment by StanAngeloff** [comment]
Nope, ignoring files manually that use `...` to have tests pass at the moment.

**Comment by redbeardcreator** [comment]
I just ran into this today. The good news is, since #202 was recently closed, @manuelpichler may be thinking about this one :smile:.

By the way, thanks @manuelpichler, for all the awesome work! :ok_hand:

**Comment by JeroenDeDauw** [comment]
+1, just ran into this as well
