### ISSUE TITLE
Self Update for Phar?

### ISSUE THREAD

**Issue by sataris** [pdepend/pdepend#207]
I think it would be a great addition for the phar to have a --selfupdate option, 

Apologies if this has already been discussed.

**Comment by manuelpichler** [comment]
Nice idea, will look into Composer how it is done there

**Comment by ravage84** [comment]
I would prefer to let tools like the dependency management tool [Composer](https://getcomposer.org/) or the PHAR installation tool [PHIVE](https://phar.io/) handle this.

@tvbeek, @AJenbo & @kylekatarnls your opinions?

**Comment by tvbeek** [comment]
I agree, also because it isn't asked again I think we can see it as not needed. (For a good working with PHIVE we need to fix #397)

If this is really wanted someone can reopen this issue.
