### ISSUE TITLE
Hacklang Depend?

### ISSUE THREAD

**Issue by skyzyx** [pdepend/pdepend#208]
Is there an interest in, or work underway to, implement support for Hack in addition to PHP?

**Comment by doublecompile** [comment]
:+1:

I'd be glad to help throw some work against such a feature implementation.

**Comment by manuelpichler** [comment]
@doublecompile are you willing to provide an initial PR for this?

**Comment by doublecompile** [comment]
@manuelpichler I'd be glad to. Please give me a couple of days to get it together.

**Comment by skyzyx** [comment]
Ping.

**Comment by manuelpichler** [comment]
Since I haven't the time to implement Hacklang support and no PR was opened for the last 1,5 years, I will close this ticket now.
