### ISSUE TITLE
php 5.6 constant syntax not supported

### ISSUE THREAD

**Issue by tystr** [pdepend/pdepend#209]
I have a constant defined like this:
```PHP
    const MONTHS = [
        'January'   => 'January',
        'February'  => 'February',
        // ...
    ];
```
pdepend errors with the following message:
`Unexpected token: =>`

In another file I have a constant defined like this:
```PHP
    const SCALAR_TYPES = ['string', 'int', 'float', 'boolean'];
```
pdepend errors with the following message:
`Unexpected token: 'int'`

**Comment by internalsystemerror** [comment]
Duplicate of https://github.com/pdepend/pdepend/issues/192

**Comment by manuelpichler** [comment]
Duplicate with #192
