### ISSUE TITLE
using Pdepend in command line task Gradle

### ISSUE THREAD

**Issue by HieronyM** [pdepend/pdepend#212]
Hi Manuel,
I think it's such a great feature that offered in PDepend.

So, i want to use it in my app.
But, when i implemented it in my Gradle build file with this command

"pdepend --jdepend-xml=$projectDir/build/logs/jdepend.xml ${projectDir}/src"

It's respond that I'm added an Invalid Directory.
Do you know something about this Manuel?

Thanks.

**Comment by manuelpichler** [comment]
Sorry, no clue. It seems that ${projectDir}/src does not exist. Is this problem still present?

**Comment by kylekatarnls** [comment]
I close this, I would re-open if we would get enough feedback.
