### ISSUE TITLE
PHP 7 support for concatenated constant values.

### ISSUE THREAD

**Issue by manuelpichler** [pdepend/pdepend#219]
This issue was taken from ticket phpmd/phpmd#295 in the [PHPMD's](https://github.com/phpmd/phpmd/issues) issue tracker.

As soon as you have a constant like

```php
const Foo = 'Foo' . PHP_EOL . 'Bar';
```

the file is not parsed.

**Comment by tiger-seo** [comment]
why it's PHP 7? in PHP 5.6 it does work as you might expect
```php
class SomeTest {
    const FIXTURES_PATH = __DIR__ . DIRECTORY_SEPARATOR . 'Fixtures' . DIRECTORY_SEPARATOR;
```

**Comment by michaelhogg** [comment]
+1

**Comment by manuelpichler** [comment]
See #238
