### ISSUE TITLE
Use pdepend.phar on Windows: Fatal error: Uncaught exception

### ISSUE THREAD

**Issue by tygrolew-gmail** [pdepend/pdepend#232]
I downloaded  pdepend.phar and put it in the main project folder.
when I try `php pdepend.phar --summary-xml=sum.xml ./src`
I get

Fatal error: Uncaught exception 'InvalidArgumentException' with message '[ERROR 4] Document is empty (in file:///C:/Users/<MY_NAME>/AppData/Local/Temp/sf2EF9E.tmp - line 1, column 1)
[ERROR 4] Start tag expected, '<' not found (in file:///C:/Users/<MY_NAME>/AppData/Local/Temp/sf2EF9E.tmp - line 1, column 1)
[ERROR 3067] Element '{http://www.w3.org/2001/XMLSchema}import': Failed to parse the XML resource 'file:///C:/Users/<MY_NAME>/AppData/Local/Temp/sf2EF9E.tmp'. (in in_memory_buffer - line 8, column 0)' in phar://<PROJECT_PATH>/pdepend.phar/vendor/symfony/config/Util/XmlUtils.php:96
Stack trace:
#0 phar://<PROJECT_PATH>/pdepend.phar/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(256): Symfony\Component\Config\Util\XmlUtils::loadFile('phar://D:/git-l..

.', Array)
#1 phar:/<PROJECT_PATH>/pdepend.phar/vendor/symfony/de in phar://<PROJECT_PATH>/pdepend.phar/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 258

**Comment by tygrolew-gmail** [comment]
In my comment, in the filepath their are missing USERNAME and PATH_TO_PROJECT because I put them in angle brackets.
but
  - file:///C:/Users//AppData/Local/Temp/sf2EF9E.tmp is really file:///C:/Users/USERNAME/AppData/Local/Temp/sf2EF9E.tmp
  - phar:///pdepend.phar/vendor/symfony/config/Util/XmlUtils.php is really phar://PATH_TO_PROJECT/pdepend.phar/vendor/symfony/config/Util/XmlUtils.php
 - and so on

**Comment by kylekatarnls** [comment]
Sorry for the delay. If you still have the issue, please provide a sample project where we can reproduce the error and I would re-open. Thanks.
