### ISSUE TITLE
Allow packages to be defined by @package annotation instead of namespace

### ISSUE THREAD

**Issue by patrickkusebauch** [pdepend/pdepend#233]
Packages in pdepend are now created based on namespaces. There is no way to switch this behavior to follow either file level or class level @package annotation.

This is problematic since with PSR-0 and PSR-4, namespace is used mainly for structural and directory organization. It means you are quite limited in your definitions of namespaces, if you want to have a reasonable directory structure.

On the other hand, the @package annotation is used to define logical groups within your codebase. This problem is also mentioned in issue #84. 

Maybe a command line option to prefer @package tags over namespace definitions?

**Comment by ravage84** [comment]
Would a namespace to package mapping in the PHP Depend configuration XML file work?

**Comment by patrickkusebauch** [comment]
I am using https://github.com/qossmic/deptrac nowadays for enforcing PHP dependencies. So I am no longer invested in resolving this issue as well as the actual implementation details.

**Comment by tvbeek** [comment]
@patrickkusebauch thanks for your fast response, I totally understand your choice, deptrac is a very useful package for this case.

Trying to re implement this in PHP Depend isn't very useful so I close this issue.
