### ISSUE TITLE
PHP Warning:  DOMDocument::load(): I/O warning : failed to load external entity 

### ISSUE THREAD

**Issue by mundoEarth** [pdepend/pdepend#241]
Hello Everyone!

 I just want to ask about pdepend.phar when I integrate my builds on gitlab an error appears after build like this: 
[pdepend] PHP Warning:  DOMDocument::load(): I/O warning : failed to load external entity "phar:///var/lib/jenkins/jobs/New%20Job%201/workspace/build/tools/pdepend.phar/src/main/php/PDepend/Report/Jdepend/chart.svg" in phar:///var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar/src/main/php/PDepend/Report/Jdepend/Chart.php on line 152
  [pdepend] PHP Stack trace:
  [pdepend] PHP   1. {main}() /var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar:0
  [pdepend] PHP   2. PDepend\TextUI\Command::main() /var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar:59
  [pdepend] PHP   3. PDepend\TextUI\Command->run() phar:///var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar/src/main/php/PDepend/TextUI/Command.php:624
  [pdepend] PHP   4. PDepend\TextUI\Runner->run() phar:///var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar/src/main/php/PDepend/TextUI/Command.php:233
  [pdepend] PHP   5. PDepend\Engine->analyze() phar:///var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar/src/main/php/PDepend/TextUI/Runner.php:314
  [pdepend] PHP   6. PDepend\Report\Jdepend\Chart->close() phar:///var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar/src/main/php/PDepend/Engine.php:341
  [pdepend] PHP   7. DOMDocument->load() phar:///var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar/src/main/php/PDepend/Report/Jdepend/Chart.php:152
  [pdepend] PHP Fatal error:  Call to a member function removeAttribute() on null in phar:///var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar/src/main/php/PDepend/Report/Jdepend/Chart.php on line 157
  [pdepend] PHP Stack trace:
  [pdepend] PHP   1. {main}() /var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar:0
  [pdepend] PHP   2. PDepend\TextUI\Command::main() /var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar:59
  [pdepend] PHP   3. PDepend\TextUI\Command->run() phar:///var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar/src/main/php/PDepend/TextUI/Command.php:624
  [pdepend] PHP   4. PDepend\TextUI\Runner->run() phar:///var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar/src/main/php/PDepend/TextUI/Command.php:233
  [pdepend] PHP   5. PDepend\Engine->analyze() phar:///var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar/src/main/php/PDepend/TextUI/Runner.php:314
  [pdepend] PHP   6. PDepend\Report\Jdepend\Chart->close() phar:///var/lib/jenkins/jobs/New Job 1/workspace/build/tools/pdepend.phar/src/main/php/PDepend/Engine.php:341
  [pdepend] Result: 255

But if I would not configure source code management that message will not display on my screen upon building the project. 
Any solution for this?

**Comment by manuelpichler** [comment]
This should be fixed already
