### ISSUE TITLE
Call to a member function removeAttribute() on null

### ISSUE THREAD

**Issue by sebastianbergmann** [pdepend/pdepend#242]
I get the following with PHP_Depend 2.2.2 and PHP 5.6. Oddly enough I do not get the error with PHP 7.0.3.

```
PHP Fatal error: Call to a member function removeAttribute() on null in phar:///path/to/pdepend.phar/src/main/php/PDepend/Report/Jdepend/Chart.php on line 157
```

**Comment by manuelpichler** [comment]
Need to compile 5.6 now. Does that error occur with any source or only with a concrete code base?

**Comment by manuelpichler** [comment]
This should be a side effect of #241, which is already fixed.
