### ISSUE TITLE
Error: Cannot create new nodes, when interval state is frozen

### ISSUE THREAD

**Issue by soda0289** [pdepend/pdepend#246]
I just downloaded pdepend 2.2.3 and was hoping it would work with PHP 7. I keep getting the following error:
Critical error:
Cannot create new nodes, when internal state is frozen.

Here is the debug output:
 pdepend.phar --debug --summary-xml=code_analysis/summary.xml --jdepend-chart=code_analysis/jdepend.svg --overview-pyramid=code_analysis/pyramid.svg src/
PDepend 2.2.3

Parsing source files:

Processing file C:\Users\reyad.attiyat\Workspace\NextGenLibraries\trunk\Ar\src\Application.php
Creating: \PDepend\Source\AST\ASTNamespace(Neovation\Ar)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($instance)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($config_dir)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($router)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($language_db)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($language_manager)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($db_manager)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($view_factory)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($error_handler)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($user_session)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($services)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($db_connection_factoriess)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($active_service)
Creating: \PDepend\Source\AST\ASTFieldDeclaration()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($debug_mode_enabled)
Creating: \PDepend\Source\AST\ASTConstantDefinition(const)
Creating: \PDepend\Source\AST\ASTConstantDeclarator(TEMPLATE_COMPILE_METHOD)
Creating: \PDepend\Source\AST\ASTComment(/**
     \* Sets the directory of the configuration files
     *
     \* @param string $config_dir
     _/)
Creating: \PDepend\Source\AST\ASTMethod(setConfigDir)
Creating: \PDepend\Source\AST\ASTFormalParameters()
Creating: \PDepend\Source\AST\ASTScalarType(string)
Creating: \PDepend\Source\AST\ASTFormalParameter()
Creating: \PDepend\Source\AST\ASTVariableDeclarator($config_dir)
Creating: \PDepend\Source\AST\ASTScope()
Creating: \PDepend\Source\AST\ASTStatement()
Creating: \PDepend\Source\AST\ASTSelfReference(Application)
Creating: \PDepend\Source\AST\ASTMemberPrimaryPrefix(::)
Creating: \PDepend\Source\AST\ASTVariable($config_dir)
Creating: \PDepend\Source\AST\ASTPropertyPostfix($config_dir)
Creating: \PDepend\Source\AST\ASTAssignmentExpression(=)
Creating: \PDepend\Source\AST\ASTVariable($config_dir)
Creating: \PDepend\Source\AST\ASTComment(/_*
     \* Returns the single instance of the Application
     */)
Creating: \PDepend\Source\AST\ASTMethod(getInstance)
Creating: \PDepend\Source\AST\ASTFormalParameters()
Creating: \PDepend\Source\AST\ASTClassOrInterfaceReference(Neovation\Ar\Application)
Creating: \PDepend\Source\AST\ASTScope()
Creating: \PDepend\Source\AST\ASTIfStatement(if)
Creating: \PDepend\Source\AST\ASTExpression()
Creating: \PDepend\Source\AST\ASTLiteral(null)
Creating: \PDepend\Source\AST\ASTExpression(===)
Creating: \PDepend\Source\AST\ASTStaticReference()
Creating: \PDepend\Source\AST\ASTMemberPrimaryPrefix(::)
Creating: \PDepend\Source\AST\ASTVariable($instance)
Creating: \PDepend\Source\AST\ASTPropertyPostfix($instance)
Creating: \PDepend\Source\AST\ASTExpression()
Creating: \PDepend\Source\AST\ASTScopeStatement()
Creating: \PDepend\Source\AST\ASTStatement()
Creating: \PDepend\Source\AST\ASTStaticReference()
Creating: \PDepend\Source\AST\ASTMemberPrimaryPrefix(::)
Creating: \PDepend\Source\AST\ASTVariable($instance)
Creating: \PDepend\Source\AST\ASTPropertyPostfix($instance)
Creating: \PDepend\Source\AST\ASTAssignmentExpression(=)
Creating: \PDepend\Source\AST\ASTAllocationExpression(new)
Creating: \PDepend\Source\AST\ASTStaticReference()
Creating: \PDepend\Source\AST\ASTArguments()
Creating: \PDepend\Source\AST\ASTReturnStatement(return)
Creating: \PDepend\Source\AST\ASTStaticReference()
Creating: \PDepend\Source\AST\ASTMemberPrimaryPrefix(::)
Creating: \PDepend\Source\AST\ASTVariable($instance)
Creating: \PDepend\Source\AST\ASTPropertyPostfix($instance)

Critical error:
Cannot create new nodes, when internal state is frozen.
#0 phar://C:/Users/reyad.attiyat/Workspace/NextGenLibraries/trunk/build_tools/pdepend/pdepend.phar/src/main/php/PDepend/TextUI/Command.php(243): PDepend\TextUI\Runner->run()
#1 phar://C:/Users/reyad.attiyat/Workspace/NextGenLibraries/trunk/build_tools/pdepend/pdepend.phar/src/main/php/PDepend/TextUI/Command.php(627): PDepend\TextUI\Command->run()
#2 C:\Users\reyad.attiyat\Workspace\NextGenLibraries\trunk\build_tools\pdepend\pdepend.phar(59): PDepend\TextUI\Command::main(Array)
#3 {main}

However if i use --without-annotations it seems to work but I do get errors like:
Unexpected token: ??

**Comment by KacerCZ** [comment]
Please use Pdepend version 2.5.0 and verify, that problem is still present.

**Comment by kylekatarnls** [comment]
I close this, I would re-open if we would get enough feedback.
