### ISSUE TITLE
ASTNode expected, ASTAnonymousClass given

### ISSUE THREAD

**Issue by fracasula** [pdepend/pdepend#250]
Hi there,

I just ran phpmd on my project with this command:

```
vendor/bin/phpmd ./ text cleancode,codesize,controversial,design,naming,unusedcode --exclude=vendor/*,Tests/app/cache/*,Tests/app/logs/*,Tests/app/AppKernel.php
```

Error below:

> PHP Catchable fatal error:  Argument 1 passed to PDepend\Source\AST\AbstractASTNode::addChild() must implement interface PDepend\Source\AST\ASTNode, instance of PDepend\Source\AST\ASTAnonymousClass given, called in /squawka/squawka-database/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php on line 214 and defined in /squawka/squawka-database/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTNode.php on line 367

Versions used:
- "phpmd/phpmd": "2.4.2"
- "pdepend/pdepend": "2.2.4"

There's anything I could do to find out how to solve this?

**Comment by aschwin** [comment]
+1 Same issue here

**Comment by edro** [comment]
+1 the same

**Comment by bezrukovp** [comment]
+1 the same

**Comment by llato** [comment]
Maybe it can help. This error occurred when anonymous class is used:

`new class()`

**Comment by fracasula** [comment]
Is this what you mean @llato ?

	$article = (new Entity\Article())
		->setTitle($title)
		->setAuthor($author);
		->setCreatedAt(new \DateTime());

All setters in my case return `$this` so it works like a charm :+1:

**Comment by dmaij** [comment]
I changed the parent class of PHPParserGeneric from PHPParserVersion70 to PHPParserVersion56 in the pdepend source (./pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserGeneric.php line 61). 

Since I am running php56, i figures this was a weird contruction and it appears to work (for me at least)

**Comment by ChrisWesterfield** [comment]
Is there already an solution in site/in Master?

**Comment by sfeni** [comment]
same here
downgraded pdepend/pdepend to version 2.2.2 worked for me

**Comment by ChrisWesterfield** [comment]
that helped thanks 👍

**Comment by SimonFolger** [comment]
dmaij´s solution worked for me aswell, thanks

**Comment by neemzy** [comment]
So one month later, are we still better off editing vendor code to work around this? :)

**Comment by ClemensWijnekus** [comment]
Neither downgrading to 2.2.2 (Cannot create nodes when, interval is in frozen state error) or setting the parser to PHP 5.6 is working for me. I run PHP 7.0.8.
Is there any other fix or workaround for this? Keeps me from getting green builds in jenkins as it cannot generate a JDepend xml report.

**Comment by mjacobus** [comment]
+1. Same as @Fjarlaegur

**Comment by Fjarlaegur** [comment]
Seems like @manuelpichler is working on a fix on a closely same named branch. Last commit 14 days ago. Maybe he can give us some insight in fixing things?

**Comment by g4z** [comment]
Thanks @Fjarlaegur. I was having the same problem until I read your comment and realises I had forgotten to use `--exclude vendor`.
