### ISSUE TITLE
Running PHPMD throws non-existent Exception

### ISSUE THREAD

**Issue by internalsystemerror** [pdepend/pdepend#253]
PHP Fatal error:  Class 'org\pdepend\reflection\exceptions\EndOfTokenStreamException' not found in /xxxxxxx/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 5568

On investigation of said line, the doctag suggests the real name of the exception class should be `\PDepend\Source\Parser\EndOfTokenStreamException`, which of course, doesnt exist. There is an exception TokenStreamEndException, however.

**Comment by manuelpichler** [comment]
Fixed with commit fed4a2e
