### ISSUE TITLE
Unsupported null coalesce operator : `Unexpected token: ??` 

### ISSUE THREAD

**Issue by marco-loche** [pdepend/pdepend#254]
An `PDepend\Source\Parser\UnexpectedTokenException` is raised when using the PHP7 operator `??` (aka null coalesce operator).

See also https://github.com/phpmd/phpmd/issues/347 and http://php.net/manual/en/language.operators.comparison.php

**Comment by wsromek** [comment]
@manuelpichler is there any chance for a solution of this issue any time soon? Thanks!

**Comment by manuelpichler** [comment]
This should be fixed with @k-jackson's PR #267
