### ISSUE TITLE
Fatal error while parsing source code, version 2.2.4

### ISSUE THREAD

**Issue by Knitter** [pdepend/pdepend#255]
Hi,
I'm trying to run pdepend for the first time against a project I inherited and it crashes with a fatal error while in the parsing process, is there a way to understand what is causing pdepend to crash? I'm assuming it is my code but lint still hasn't showed any useful info and given that the error occurs inside pdepend I can't seem to figure out what is causing it. Any debug flag I can use or something that allows me to know what file is being parsed?
I'm using version 2.2.4 and the output is as follows:

> pdepend:
>  [pdepend] PDepend 2.2.4
>  [pdepend]
>  [pdepend] Parsing source files:
>  [pdepend] ............................................................    60
>  [pdepend] ............................................................   120
>  [pdepend] ............................................................   180
>  [pdepend] ............................................................   240
>  [pdepend] ............................................................   300
>  [pdepend] ............................................................   360
>  [pdepend] ............................................................   420
>  [pdepend] PHP Catchable fatal error:  Argument 1 passed to PDepend\Source\Language\PHP\AbstractPHPParser::parseAssignmentExpression() must implement interface PDepend\Source\AST\ASTNode, null given, called in /vagrant/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 2736 and defined in /vagrant/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 4301

**Comment by Knitter** [comment]
I found the code that was crashing pdepend, this was in one of the files being parsed (a view file with PHP and HTML):

> href="<? = $base . '/catalogos/'. $var->attribute ?>

Notice the space after the opening PHP tag, making it an invalid opening tag.

**Comment by KacerCZ** [comment]
Can you please verify, if this problem is still present in Pdepend 2.5.0.

**Comment by kylekatarnls** [comment]
I close this, I would re-open if we would get enough feedback.
