### ISSUE TITLE
pdepend getting stuck when generating the log files

### ISSUE THREAD

**Issue by lferro9000** [pdepend/pdepend#257]
pdepend:
  [pdepend] PDepend 2.2.3
  [pdepend] 
  [pdepend] Parsing source files:
  [pdepend] ............................................................    60
  [pdepend] ............................................................   120
  [pdepend] ............................................................   180
  [pdepend] ............................................................   240
  [pdepend] ..................                                             258
  [pdepend] 
  [pdepend] Calculating Dependency metrics:
  [pdepend] ............................................................  1200
  [pdepend] ............................................................  2400
  [pdepend] ............................................................  3600
  [pdepend] ....................                                          4006
  [pdepend] 
  [pdepend] Calculating Coupling metrics:
  [pdepend] ............................................................  1200
  [pdepend] ............................................................  2400
  [pdepend] ............................................................  3600
  [pdepend] ............................................................  4800
  [pdepend] ........................................................      5922
  [pdepend] 
  [pdepend] Calculating Cyclomatic Complexity metrics:
  [pdepend] ............................................................  1200
  [pdepend] ............................................................  2400
  [pdepend] ............................................................  3600
  [pdepend] ............................................................  4800
  [pdepend] .....................................................         5865
  [pdepend] 
  [pdepend] Calculating Inheritance metrics:
  [pdepend] .........................                                      505
  [pdepend] 
  [pdepend] Calculating Node Count metrics:
  [pdepend] ............................................................  1200
  [pdepend] ............................................................  2400
  [pdepend] ............................................................  3600
  [pdepend] ....................                                          4006
  [pdepend] 
  [pdepend] Calculating Node Loc metrics:
  [pdepend] ............................................................  1200
  [pdepend] ............................................................  2400
  [pdepend] ............................................................  3600
  [pdepend] ..................................                            4288
  [pdepend] 
  [pdepend] Generating pdepend log files, this may take a moment.

Then the process just gets stuck and doesn't finish at all. This happens intermitently. The process is being run through Jenkins / Ant as per http://jenkins-php.org/ configuration settings.

Is any other way to generate some useful output of the issue to help track this bug out?

**Comment by KacerCZ** [comment]
Can you please chek if this problem is still present in PDepend 2.5 (latest version).

**Comment by kylekatarnls** [comment]
I close this, I would re-open if we would get enough feedback.
