### ISSUE TITLE
NPath calculations for conditional expressions (ternary operators) is incorrect

### ISSUE THREAD

**Issue by offsides** [pdepend/pdepend#261]
There are two problems with the calculation of the NPath value of a conditional expression, that is (expr1) ? (expr2) : (expr3), where the NPath formula of NP(?) = NP(expr1) + NP(expr2) + NP(expr3) + 2.  The first is that the NPath value of expr1 is not calculated at all, giving a false result for any case where expr1 is not a simple expression with no conditionals in it.  The second is that the implementation of the conditional expression formula is flat out incorrect, though that may inherited from precursor implementations (and I admit to not having done huge amounts of investigation).

As proof of the first problem, I submit the following base code:

``` php
function npathtest()
{
    $a = int(rand(2));
    $b = int(rand(3));
    $c = int(rand(4));
    $d = int(rand(5));
    $e = int(rand(6));
    $f = int(rand(7));
    if ($a && $b && $c && $d) { # NPath = 5
        ++$a %= 2;
    }
    if ($a && $b && $c && $d) { # NPath = 5
        ++$a %= 2;
    }
    if ($a) { # NPath = 2
        ++$a %= 2;
    }
    if ($a) { # NPath = 2
        ++$a %= 2;
    }
    if ($a) { # NPath = 2
        ++$a %= 2;
    }

    return $a; # Total NPath = 200

}
```

The above code has an NPath value of 200, which is used to demonstrate both how boolean expressions should evaluate and to make PHPMD spit out results for me when calling pdepend (since that's what I was using when I first encountered this issue).  Now, I'll add a ternary operator before the return statement, like this:

`$a = ($a) ? $e : $f; # NPath = 5(2)`

and the NPath complexity jumps from 200 to 1000, a factor of 5.  It should really only be a factor of 2, but I'll address that shortly.  First, I'm going to change value of the first expression to include additional boolean terms, which should increase the NPath value for each one I add.  Let's start simple:

`$a = ($a && $b) ? $e : $f; # NPath should be 6(3), is 5`

Based on the formula, the NPath value of expr1 should increase by 1, meaning the calculated value should be 1200.  However it isn't, it's still 1000.  Let's see if adding another term changes something:

`$a = ($a && $b && $c) ? $e : $f; # NPath should be 7(4), is 5`

Nope, still 1000.  And it stays that way no matter how many terms I add:

`$a = ($a && $b && $c && $d) ? $e : $f; # NPath should be 8(5), is 5`
`$a = ($a && $b && $c && $d && $e) ? $e : $f; NPath should be 9(6), is 5`
`$a = ($a && $b && $c && $d && $e && $f) ? $e : $f; # NPath should be 10(7), is 5`
`$a = ($a && $b && $c && $d && $e && $f || ($c && $d && $e)) ? $e : $f; # NPath should be 13(10), is 5`

All of the above lines added individually to the original function have the same NPath complexity, which is clearly incorrect.  I have not dug deep into the logic of the code yet, but I believe this comes from the fact that the NPath of a conditional expression does not include looking at the value of expr1, but only the child NPath values that come after the '?' (expr2 and expr3).

However, there's still a rather big flaw in the calculation of NP(?).  According to the original paper by Namjeh, `NP(?) = NP(expr1) + NP(expr2) + NP(expr3) + 2` - the '+2' accounting for the fact that in addition to any possible paths within the expressions themselves, there were two possible paths for the conditional: one that led to expr2, and the other that led to expr3.  The problem with the implementation is twofold.  The simpler piece to resolve comes from this code, in NPathComplexityAnalyzer.php in the function visitConditionalExpression:

```
   foreach ($node->getChildren() as $child) {
    if (($cn = $this->sumComplexity($child)) === '0') {
        $cn = '1';
    }
    $npath = MathUtil::add($npath, $cn);
}
```

The if statement executed after the complexity of each child node is calculated ensures that the minimum complexity of the expressions expr2 and expr3 is 1.  However, according to Namjeh, is is incorrect!  According to the original article, "NP(expression) = number of && and || operators in the expression."  While it is true that the NP value of any component that is multiplied MUST be greater than 0 in order to avoid invalidating the entire calculation, the '+2' at the end of the formula for NP(?) ensures that even if the NP values for all three expressions is 0, the total NP value is going to be non-zero.  As a result, that entire if block is incorrect and should be removed.

This can be further validated by putting boolean expressions into expr2 and/or expr3.  For example, if you change the line to:

`$a = ($a) ? ($a && $e) : $f; # NPath should be 6(3), is 5`

the resulting NPath complexity should increase, yet it remains the same.  However, adding a second logical operator like so:

`$a = ($a) ? ($a && $b && $e) : $f; NPath should be 7(4), is 6`

does increase the NPath complexity to 1200.  The same holds true for the expression after the ':', for obvious reasons.

However, eliminating the artificial floor of 1 only partially fixes the calculation.  This is because the initial path values set in visitConditionalExpression also have an artificially high floor:

```
// New PHP 5.3 ifsetor-operator $x ?: $y
if (count($node->getChildren()) === 1) {
    $npath = '4';
} else {
   $npath = '3';
}
```

The base value of NP(?) is 2, plus the NP() of each expression.  In both cases, it explicitly assumes that the value of NP(expr1) == 1, as it adds 1 if there's 2 children, or 2 if there's only 1.  Since with the new ?: operator the expression `$x ?: $y` is equavalent to `$x ? $x : $y`, this initial value is only valid if NP(expr1) == 1, but is invalid otherwise.  In the examples above, NP($x) == 0, not 1, giving the same artificial floor problem as is caused by the if statement inside the foreach loop.  But more importantly, it's tied to the first problem of NP(expr1) never being calculated.

A proper solution would be to pass NP(expr1) as the data parameter to visitConditionalExpression, and change the entire function as follows:

```
public function visitConditionalExpression($node, $data)
{
    $npath = $data;
    // New PHP 5.3 ifsetor-operator $x ?: $y
    if (count($node->getChildren()) === 1) {
        $npath = MathUtil::mul($npath, '2');
    }
    foreach ($node->getChildren() as $child) {
        $npath = MathUtil::add($npath, $cn);
    }

    return $npath;
}
```

Again, I'm not sure how to get the value of expr1 and pass it to visitConditionalExpression, but hopefully it's not a hard thing for someone who's familiar with the code to figure out now that you're looking for it.  For reference, this is using pdepend 2.2.4 installed via the EPEL repository for RHEL 7, which I have verified does not make any code changes other than some path changes to the autoload setup.

**Comment by offsides** [comment]
Correction:  the updated visitConditionalExpression function should be changed as follows:

```
public function visitConditionalExpression($node, $data)
{
    $npath = $data;
    // New PHP 5.3 ifsetor-operator $x ?: $y
    if (count($node->getChildren()) === 1) {
        $npath = MathUtil::mul($npath, '2');
    }
    foreach ($node->getChildren() as $child) {
        $cn = $this->sumComplexity($child);
        $npath = MathUtil::add($npath, $cn);
    }

    return $npath;
}
```

In eliminating the if statement, I also eliminated the function call to get the complexity of the child node.  Oops :)

**Comment by offsides** [comment]
And after not hearing anything, I did some digging and figured it out.  I'll put in a pull request once I figure it out :)  For reference, the updated function is this, which also re-adds the '+2' at the end since I forgot it before...

```
public function visitConditionalExpression($node, $data)
{
    // Calculate the complexity of the condition
    $parent = $node->getParent()->getChild(0);
    $npath = $this->sumComplexity($parent);
    // New PHP 5.3 ifsetor-operator $x ?: $y
    if (count($node->getChildren()) === 1) {
        $npath = MathUtil::mul($npath, '2');
    }
    foreach ($node->getChildren() as $child) {
        $cn = $this->sumComplexity($child);
        $npath = MathUtil::add($npath, $cn);
    }
    $npath = MathUtil::add($npath, '2');

    return $npath;
}
```

**Comment by offsides** [comment]
Pull request #263 created.

**Comment by yoosefi** [comment]
hoo boy here we go again. best of luck :+1:

**Comment by manuelpichler** [comment]
PR merged. thx for your contribution

**Comment by offsides** [comment]
You're welcome, and thanks for merging it.
