### ISSUE TITLE
PHP7 anonymous class parser error

### ISSUE THREAD

**Issue by midan888** [pdepend/pdepend#265]
Pasting stack trace, its PHP7. the argument has different interface when parsing anonymous classes

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PDepend\Source\AST\AbstractASTNode::addChild() must implement interface PDepend\Source\AST\ASTNode, instance of PDepend\Source\AST\ASTAnonymousClass given, called in /var/lib/jenkins/workspace/taymo-api/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php on line 214 and defined in /var/lib/jenkins/workspace/taymo-api/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTNode.php:367

**Comment by jimdelois** [comment]
Duplicate of: https://github.com/pdepend/pdepend/issues/250

**Comment by manuelpichler** [comment]
Resolved in 2111906
