### ISSUE TITLE
pdepend "The parser has reached an invalid state" on parent call in if statement

### ISSUE THREAD

**Issue by Musiksammler** [pdepend/pdepend#266]
Hello!

Propel2's autogeneration of model php files builds classes like this:

```
<?php
abstract class FooBar implements ActiveRecordInterface
{
    /**
     * Code to be run before persisting the object
     * @param  ConnectionInterface $con
     * @return boolean
     */
    public function preSave(ConnectionInterface $con = null)
    {
        if (is_callable('parent::preSave')) {
            return parent::preSave($con);
        }
        return true;
    }

    /**
     * Code to be run after persisting the object
     * @param ConnectionInterface $con
     */
    public function postSave(ConnectionInterface $con = null)
    {
        if (is_callable('parent::postSave')) {
            parent::postSave($con);
        }
    }
}
```

Pdepend doesn't seem to get that the "parent" call is connected to the "if" statement and throws the following error:

The parser has reached an invalid state near line "..." in file "...".> Please check the following conditions: The keyword "parent" was used as type hint but the class "FooBar" does not declare a parent.

Is there any way to get around this?

**Comment by manuelpichler** [comment]
This exception is expected behavior to inform a developer that his class uses parent even if no parent class exists. And in your example there is no parent class, just an implemented interface.
