### ISSUE TITLE
Unexpected token: ... (variable number of function arguments)

### ISSUE THREAD

**Issue by karlomikus** [pdepend/pdepend#270]
Generating pdepend log files, this may take a moment.

The following errors occured:
Unexpected token: ..., line: 100, col: 43, file:

The line is: `public function allows($ability, ... $options)`

More info on http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list

Happens on 2.2.4.

**Comment by manuelpichler** [comment]
This should work at least with PDepend 2.3
