### ISSUE TITLE
Unexpected token: ??, Logical Operators

### ISSUE THREAD

**Issue by bizmate** [pdepend/pdepend#271]
Error on Logical operator ??

```
Unexpected token: ??, line: 126, col: 64, file: ..Auth.php.
```

and the line looks like

```
$options['json'] = array_merge($json, $options['json'] ?? []);
```

on versino pdepend/pdepend                        2.2.4

**Comment by jdeniau** [comment]
Seems to be fixed in master branch  (see 516539c7e76368555a785974bae1d71cc9c0f8a8 ) but #270 isn't :|

**Comment by cabdesigns** [comment]
Given this is in master now, is there any idea when the tag will get created? Is this something a contributor (other than core) can assist with?

Thanks for the great work on this project!

**Comment by manuelpichler** [comment]
New release with fix is available
