### ISSUE TITLE
Use @inheritdoc instead of copying docblocks for methods

### ISSUE THREAD

**Issue by kalimatas** [pdepend/pdepend#273]
Consider, for example, `PDepend\ProcessListener` interface and one of its implementations `PDepend\TextUI\ResultPrinter`. The docblock for all methods is just copied from the interface definition, though instead `@inheritdoc` annotation can be used.

This can be done everywhere, where it is applicable. I just wanted to know, if you will accept such a MR, before I start doing that.

**Comment by manuelpichler** [comment]
@kalimatas yes I would

**Comment by manuelpichler** [comment]
Question already answered
