### ISSUE TITLE
ASTConstantDeclarator crash on array concat with named keys

### ISSUE THREAD

**Issue by AJenbo** [pdepend/pdepend#299]
This will crash pdepend

```
class Test
{
    const A = [];
    const B = self::A + ['a' => 1];
}
```

Log:
`PDepend @package_version@

Parsing source files:
.......
Creating: \PDepend\Source\AST\ASTNamespace(Kontent_Auth\Adapter)......................
Creating: \PDepend\Source\AST\ASTNamespace(Site_Controller\Kontent_Controller).......
Creating: \PDepend\Source\AST\ASTNamespace(Kontent_Field)....
Processing file /home/ajenbo/code/test.php
Creating: \PDepend\Source\AST\ASTConstantDefinition(const)
Creating: \PDepend\Source\AST\ASTConstantDeclarator(A)
Creating: \PDepend\Source\AST\ASTArray()
Creating: \PDepend\Source\AST\ASTConstantDefinition(const)
Creating: \PDepend\Source\AST\ASTConstantDeclarator(B)PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PDepend\Source\AST\ASTConstantDeclarator::setValue() must be an instance of PDepend\Source\AST\ASTValue, null given, called in /usr/share/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 6118 and defined in /usr/share/php/PDepend/Source/AST/ASTConstantDeclarator.php:107
Stack trace:
#0 /usr/share/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6118): PDepend\Source\AST\ASTConstantDeclarator->setValue(NULL)
#1 /usr/share/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6053): PDepend\Source\Language\PHP\AbstractPHPParser->parseConstantDeclarator()
#2 /usr/share/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(839): PDepend\Source\Language\PHP\AbstractPHPParser->parseConstantDefinition()
#3 /usr/share/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(666): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody(Object(PDepend\Source\AST\ASTClass))
#4 /usr/share/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5669): PDepend\Sour in /usr/share/php/PDepend/Source/AST/ASTConstantDeclarator.php on line 107`

**Comment by peldax** [comment]
Hi, I have this issue too, I am unable to analyze my code using pdepend nor phpmd.
My code snippet:
```
public const TEST =
        self::CONSTANT + [
        'test1' => 'Test1',
        'test2' => 'Test2'
    ];
```

**Comment by IvanAlekseevichPopov** [comment]
Same problem.

**Comment by kylekatarnls** [comment]
I will try to fix this for the version 2.7.0.

**Comment by kylekatarnls** [comment]
This should fix it: #416

**Comment by kylekatarnls** [comment]
You can give it a try with:
```
composer require pdepend/pdepend:dev-feature/issue-299-array-concat-constant
```

**Comment by kylekatarnls** [comment]
Fixed in 2.6.1.

**Comment by dhampik** [comment]
I'm trying to run phpmd 2.8.1 which uses pdepend 2.7.0 on the very first test in this issue:
~~~
class Test
{
    const A = [];
    const B = self::A + ['a' => 1];
}
~~~

And it fails with the same error. Can someone actually confirm that issue is fixed and problem is on my side?
I'm running php 7.3, if it matters.

**Comment by kylekatarnls** [comment]
I took your exact code to write the test that is now passing:
https://github.com/pdepend/pdepend/commit/4fe9d78b9dd53626c9a9db5bb8c22cbffa8aca5e#diff-50384b8ceb7175aac067ce8fe5164d98

Are you sure about the version? (Local version if you run `./vendor/bin/phpmd` / Global version if you run `phpmd`)

**Comment by dhampik** [comment]
Not sure about the passing test, but I just took composer docker image, ran a bunch of commands and this is what I got:
~~~
/app # php -v
PHP 7.4.2 (cli) (built: Jan 24 2020 07:11:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
/app # composer --version
Composer version 1.9.2 2020-01-14 16:30:31
/app # composer require pdepend/pdepend
Using version ^2.7 for pdepend/pdepend
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-ctype (v1.13.1): Downloading (100%)         
  - Installing symfony/filesystem (v5.0.3): Downloading (100%)         
  - Installing symfony/config (v5.0.3): Downloading (100%)         
  - Installing psr/container (1.0.0): Downloading (100%)         
  - Installing symfony/service-contracts (v2.0.1): Downloading (100%)         
  - Installing symfony/dependency-injection (v5.0.3): Downloading (100%)         
  - Installing pdepend/pdepend (2.7.0): Downloading (100%)         
symfony/config suggests installing symfony/yaml (To use the yaml reference dumper)
symfony/dependency-injection suggests installing symfony/yaml
symfony/dependency-injection suggests installing symfony/finder (For using double-star glob patterns or when GLOB_BRACE portability is required)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
Writing lock file
Generating autoload files
/app # vendor/bin/pdepend --version
PDepend 2.7.0

/app # echo "<?php class Test { const A = []; const B = self::A + ['a' => 1]; }" > Test.php
/app # vendor/bin/pdepend --summary-xml=/tmp/test.xml Test.php
PDepend 2.7.0

Parsing source files:

Fatal error: Uncaught TypeError: Argument 1 passed to PDepend\Source\AST\ASTConstantDeclarator::setValue() must be an instance of PDepend\Source\AST\ASTValue, null given, called in /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 6405 and defined in /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTConstantDeclarator.php:107
Stack trace:
#0 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6405): PDepend\Source\AST\ASTConstantDeclarator->setValue(NULL)
#1 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6333): PDepend\Source\Language\PHP\AbstractPHPParser->parseConstantDeclarator()
#2 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(891): PDepend\Source\Language\PHP\AbstractPHPParser->parseConstantDefinition()
#3 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(718): PDepend\Source\Language\PHP\A in /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTConstantDeclarator.php on line 107
~~~

So, looks like issue still persist.

**Comment by kylekatarnls** [comment]
Hello, I found why the test pass: because it's tested with PHP 5.6 level: the version in which this syntax was introduced, and it properly works with the `PHPParserVersion56` but it fails with 7.4 level so it's due to some of the features in the parsers chain. I will no be able to debug it.
