### ISSUE TITLE
Unexpected token error calling invokable property

### ISSUE THREAD

**Issue by Garbee** [pdepend/pdepend#301]
This seems to throw an "unexpected token" exception when you are calling an invokable object that is a property of a class. In the sample files below, the error is thrown from the `index` method of the `Controller` class where the call is being made. It seems to be because the syntax isn't being handled properly. Other tooling such as PHPStan, PHPStorm, and PHP CS don't see a token problem and the code executes properly within PHP itself.

<details>
<summary>InjectedThing.php</summary>

```php
<?php

namespace App;

class InjectedThing {
    public function __invoke(string $name, string $place): void
    {
        echo "Hello $place, $name";
    }
}
```

</details>

<details>
<summary>Controller.php</summary>

```php
<?php

namespace App;

class Controller
{
    /** @var \App\InjectedThing $thing */
    private $thing;

    public function __construct()
    {
        $this->thing = new InjectedThing();
    }

    public function index(): void
    {
        ($this->thing)('Garbee', 'Universe');
     }
}
```

</details>

**Comment by raykolbe** [comment]
Experienced this as well. Currently using version 2.5.0.

**Comment by roukmoute** [comment]
Any news about that?

**Comment by Nacoma** [comment]
This is still present in 2.5.2.

It passes with a single argument to the callback but fails when encountering the comma.

**Comment by kylekatarnls** [comment]
Will be fixed in the next version of PDepend.
