### ISSUE TITLE
Parameter must be an array or an object that implements Countable (PHP 7.2)

### ISSUE THREAD

**Issue by SailorMax** [pdepend/pdepend#310]
PHP 7.2 alpha on some cases output error:
Warning: count(): Parameter must be an array or an object that implements Countable in pdepend/src/main/php/PDepend/Metrics/Analyzer/InheritanceAnalyzer.php on line 204

Looks like sometimes `rootClasses` property here can be null?
https://github.com/pdepend/pdepend/blob/master/src/main/php/PDepend/Metrics/Analyzer/InheritanceAnalyzer.php#L204

Can you add check property type before use it as array?

**Comment by emirb** [comment]
Fixed by https://github.com/pdepend/pdepend/pull/303
