### ISSUE TITLE
ERROR: cannot verify static.pdepend.org's certificate, issued by '/C=US/O=Let\'s Encrypt/CN=Let\'s Encrypt Authority X3':   Issued certificate has expired.

### ISSUE THREAD

**Issue by jpswade** [pdepend/pdepend#315]
Resolving static.pdepend.org (static.pdepend.org)... 78.47.238.172
Connecting to static.pdepend.org (static.pdepend.org)|78.47.238.172|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://static.pdepend.org/php/latest/pdepend.phar [following]
--2017-08-27 11:56:10--  https://static.pdepend.org/php/latest/pdepend.phar
Connecting to static.pdepend.org (static.pdepend.org)|78.47.238.172|:443... connected.
ERROR: cannot verify static.pdepend.org's certificate, issued by '/C=US/O=Let\'s Encrypt/CN=Let\'s Encrypt Authority X3':
  Issued certificate has expired.
To connect to static.pdepend.org insecurely, use `--no-check-certificate'.

**Comment by emirb** [comment]
Certificate has been replaced in the meantime and the current one expires on the 4th of March 2018.
