### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by emirb** [pdepend/pdepend#324]
Latest commit to master is from 19th of January. Lots of issues regarding PHP 7.1 support and 7.2 is already coming out next month. 

Is the project abandoned?

**Comment by mmucklo** [comment]
Same question...?  Anyone in touch with the maintainer?

**Comment by Rockstar04** [comment]
@manuelpichler ?

**Comment by Rockstar04** [comment]
@roukmoute @babaorum

**Comment by roukmoute** [comment]
@babaorum and me are not on the project.
We have no idea if the project is always maintained.

We hope!

**Comment by Rockstar04** [comment]
Sorry for that then, I was looking through issues and PR's with commends to see if anyone else was listed as a collaborator. I saw your names on reviews so I was hoping you has repo access.

**Comment by torkiljohnsen** [comment]
Looks a bit dead to me… What other replacements do we have out there for this type of static code analysis?

**Comment by roukmoute** [comment]
I don't know but it's a project that could be cool to take up again.

**Comment by manuelpichler** [comment]
Since I am really busy and don't have the time to work on this project I would be really happy if someone is interested in becoming part of the pdepend organisation. @emirb @mmucklo @Rockstar04 @roukmoute @torkiljohnsen

**Comment by roukmoute** [comment]
Thanks to your answer @manuelpichler!

I'm very interested but if anyone have more experience with this lib, it's not a problem.
It could take me some time before to be operationnal.

**Comment by Rockstar04** [comment]
I would absolutely help maintain the project.

**Comment by KacerCZ** [comment]
@manuelpichler @emirb  Can you please add me to pdepend organization to be able to help with issue clean-up (add tags to issues, assign milestones).

**Comment by emirb** [comment]
@KacerCZ Thank you for your recent and accepted contributions to the project. Welcome to the organization! :-) 

I will close the issue as the project is picking up on the velocity recently.

**Comment by roukmoute** [comment]
Now the project is restarted, please improve many things like website, readme or **new release** :)
