### ISSUE TITLE
Add configuration file for PHP_CodeSniffer

### ISSUE THREAD

**Issue by KacerCZ** [pdepend/pdepend#334]
I'd like to add configuration file for PHP_CodeSniffer so coding style can be checked easily - https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file

Which standard is used for this project? Is it PSR2 or some specific configuration is used?

**Comment by emirb** [comment]
AFAIK it is standard PSR2.

**Comment by KacerCZ** [comment]
Thanks.
PSR2 is also mentioned in file build.properties and after running check with PSR2 rules the code was OK.
