### ISSUE TITLE
[2.5.1] missing changelog and build.properties

### ISSUE THREAD

**Issue by remicollet** [pdepend/pdepend#337]
Changelog for 2.5.1 is missing (only 2.5.0)

build.properties still on 2.5.0 so some test are failing.

There were 5 failures:

```
1) PDepend\TextUI\CommandTest::testPrintVersion
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'PDepend 2.5.0
+'PDepend 2.5.1
 
.... etc ....
 '

```

**Comment by emirb** [comment]
Thanks for reporting, I've removed the tag in the meantime, and I've opened a PR for 2.5.1. Waiting for tests result. https://github.com/pdepend/pdepend/pull/338
