### ISSUE TITLE
Support object type from PHP 7.2

### ISSUE THREAD

**Issue by KacerCZ** [pdepend/pdepend#346]
PHP 7.2 adds type `object` 
See http://php.net/manual/en/migration72.new-features.php

**Comment by kylekatarnls** [comment]
Hi, as proved by this test: #406 this is already supported.

Do you need something more in the public API? I quickly thought about `isObject()` method similar to `isArray()` but this is ambiguous because class typehints are also "object".

I will re-open if you think we need something more.
