### ISSUE TITLE
Lack of short list syntax support (PHP 7.1)

### ISSUE THREAD

**Issue by emirb** [pdepend/pdepend#353]
https://wiki.php.net/rfc/short_list_syntax

**Comment by HEKET313** [comment]
Also such syntax is not supported:

`
foreach($array as $i => ['name' => $name]) {
}
`

which is equivalent

`
foreach($array as $i => $item) {
    $name = $item['name']
}
`

**Comment by tvbeek** [comment]
This will be handled in #383
