### ISSUE TITLE
Unknown option --jdepend-chart

### ISSUE THREAD

**Issue by nick-zh** [pdepend/pdepend#355]
Somehow i get an unknown option since i updated to 2.5.1, this might be me, but i dont know what i did wrong. Also i see in the services.xml that this option should still exist, right?

**Comment by bakkerpeter** [comment]
Experiencing the same, having problems with this since the 2.5.1 release. Downgrading to 2.5.0 fixed the problems for now. 

`Unknown option '--jdepend-chart' given.`

**Comment by nicodmf** [comment]
Same here
