### ISSUE TITLE
Unexpected token: NEW 

### ISSUE THREAD

**Issue by vitalyiegorov** [pdepend/pdepend#370]
@emirb 
```
The following errors occurred:
Unexpected token: NEW, line: 105, col: 51, file: ...
```
https://github.com/phpmd/phpmd/issues/421

**Comment by kylekatarnls** [comment]
Hi, this is fixed in [2.6.0-beta.1](https://github.com/pdepend/pdepend/releases/tag/2.6.0-beta.1)

Will be soon released as a stable version.
