### ISSUE TITLE
Anonymous function not supported

### ISSUE THREAD

**Issue by tlan16** [pdepend/pdepend#394]
- PHP Depend version: 2.5.2
- PHP Version: 7.3.8
- Installation type: composer
- Operating System / Distribution & Version: `Linux Laptop 5.1.21-1-MANJARO #1 SMP PREEMPT Sun Jul 28 09:33:43 UTC 2019 x86_64 GNU/Linux`

### Current Behavior
Use of anonymous function with parameter cause `Unexpected token: ,, `

### Expected Behavior
No complain about the syntax. 

#### PHP source code
```php
<?php
declare(strict_types=1);

class ClassA
{
    public function __invoke(string $toSay1, string $toSay2)
    {
        echo $toSay1 . PHP_EOL . $toSay2 . PHP_EOL;
    }
}

class ClassB
{
    public $classA;

    public function __construct()
    {
        $this->classA = new ClassA();
    }
}

$classB = new ClassB();
($classB->classA)(
    'Hello1',
    'Hello2'
);
```
#### Execute php code
```bash
➜  ~ php /home/tlan16/Documents/dabus/integrator-framework/src/test.php
Hello1
Hello2
```
#### Execute pdepend
```bash
➜  ~ pdepend --jdepend-xml=/tmp/1.xml /home/tlan16/Documents/dabus/integrator-framework/src/test.php
PDepend 2.5.2

Parsing source files:
.                                                                1

Calculating Dependency metrics:
                                                                 5

Generating pdepend log files, this may take a moment.

The following error occurred:
Unexpected token: ,, line: 24, col: 13, file: /home/tlan16/Documents/dabus/integrator-framework/src/test.php.


Time: 0:00:00; Memory: 6.00Mb
```

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by kylekatarnls** [comment]
Solved in PDepend 2.6.0.

Current output for this code is now:
```
PDepend 2.6.1

Parsing source files:
.                                                                1

Calculating Dependency metrics:
                                                                 5

Generating pdepend log files, this may take a moment.

Time: 0:00:00; Memory: 6.00Mb
```
