### ISSUE TITLE
Allow Symfony 5

### ISSUE THREAD

**Issue by cobyl** [pdepend/pdepend#399]

**Comment by kylekatarnls** [comment]
PR already open: https://github.com/pdepend/pdepend/pull/398

**Comment by garak** [comment]
You should not close issues before related PR is merged: it looks like issue is solved (but clearly is not)

**Comment by kylekatarnls** [comment]
When issues are opened before the PR, it makes sense, but the issues about Symfony opened after the PR added no value in their content, so I closed them, and things to be discussed can be discussed on the PR.

**Comment by garak** [comment]
So, people don't find an open issue and think problem still needs to be addressed. And you find yourself keeping closing duplicated issues...

**Comment by kylekatarnls** [comment]
PRs page are here to list ongoing work:
https://github.com/pdepend/pdepend/pulls

**Comment by garak** [comment]
Maybe my experience on GitHub is limited, but I noticed that all repository maintainers keep an issue open until related PR is merged. So, I thought this could be an expected behaviour.
Probably I'm wrong.

**Comment by kylekatarnls** [comment]
I sent PRs on a ton of projects, including Symfony and Laravel, and some of them were not related to any open issue, they were discussed on the PR comments directly then merged. If I take the last 5 PRs on Symfony:
34825 -> issue related
34814 -> no issue related
34819 -> issue related
34812 -> no issue related
34823 -> no issue related

They did not feel the need to open issues for 24814, 34812 and 24823. And I don't feel the necessity of it neither.

Projects maintainers may open a new issue for each PR opened that is not related to an existing issue or may require contributors to create it before sending a PR but project with such rule as mandatory are not so common.

Last thing when having such rules is: who will do the extra work?

**Comment by garak** [comment]
I didn't say that you need an open issue for each PR.
I just said that if there's an open PR **and** an open issue, closing the issue before merging the PR is not fair.

**Comment by kylekatarnls** [comment]
I understand your point. And I apologize to @cobyl if it feels closing this issue like a blame. It's not. I know the red light may have this effect. But for us a PR is just an issue with code and we recommend to check https://github.com/pdepend/pdepend/issues?utf8=%E2%9C%93&q=is%3Aopen for both PR and issues together. We just prefer to keep only 1 stream of discussion (if issue opened first, we keep the issue, else we keep the PR).

**Comment by kylekatarnls** [comment]
Fixed in 2.6.1.
