### ISSUE TITLE
Up symfony version for 5

### ISSUE THREAD

**Issue by des1roer** [pdepend/pdepend#401]
- PHP Depend version: 2.5.2
- PHP Version: 7.4
- Installation type: composer
- Operating System / Distribution & Version: Ubuntu

Fix symfony version for 5

**Comment by kylekatarnls** [comment]
Duplicate of #398

**Comment by cawolf** [comment]
Hi again,

thanks for your effort, but was there maybe an error when releasing 2.6.0? `composer` updates fail on our side, because in https://github.com/pdepend/pdepend/blob/2.6.0/composer.json , there is still no symfony 5 supported.

    Problem 1
    - pdepend/pdepend 2.6.0 requires symfony/dependency-injection ^2.3.0|^3|^4 -> satisfiable by symfony/dependency-injection[...]

**Comment by kylekatarnls** [comment]
Fixed in 2.6.1.
