### ISSUE TITLE
Add a branch-alias

### ISSUE THREAD

**Issue by garak** [pdepend/pdepend#403]
I suggest the possibility to add a `branch-alias` entry to composer.json, pointing to next release (currently 2.6, if I understand correctly milestones).
This would let users to test latest addition in master without waiting for next release, also giving the opportunity to find possible problems before next version is actually released.

I can provide a PR, if needed.

**Comment by kylekatarnls** [comment]
I approve. PR is very welcome. Please use the version `2.x-dev`

Thanks a lot.
