### ISSUE TITLE
Typo in Github repository description

### ISSUE THREAD

**Issue by MidnightDesign** [pdepend/pdepend#417]
It's _adaptation_, not _adaption_. : )

**Comment by tvbeek** [comment]
Nice spotted, this is something for @ravage84

**Comment by MidnightDesign** [comment]
...and while you're at it: "in terms of", not "in the terms of".

**Comment by ravage84** [comment]
@MidnightDesign thanks for pointing that out.

I guess both words are valid in this case, as they are synonyms, it seems.

https://www.dict.cc/?s=adaptation
https://www.dict.cc/?s=adaption

https://www.merriam-webster.com/dictionary/adaption
https://www.merriam-webster.com/dictionary/adaptation

https://www.dictionary.com/browse/adaption

But I agree about the superfluous "the". Fixed that.

@jakzal & @MarkVaughn  can you help us non-native English speakers out, please?

**Comment by jakzal** [comment]
I'm no native English speaker, but I think "adaptation" is more common. 

https://wikidiff.com/adaption/adaptation
https://www.dailywritingtips.com/adaption-vs-adaptation/

**Comment by MidnightDesign** [comment]
![image](https://user-images.githubusercontent.com/743172/70839406-ee057f80-1e0c-11ea-89fb-2eb9a6659390.png)
 This : )

**Comment by ravage84** [comment]
Fixed
