### ISSUE TITLE
Implement the ABC metric

### ISSUE THREAD

**Issue by manuelpichler** [pdepend/pdepend#45]

**Comment by AJenbo** [comment]
For reference this is an alternative to LOC: https://en.wikipedia.org/wiki/ABC_Software_Metric

I think it's a good suggestion, but it would be good to know how popular this metric is and also to have a more fleshed out description of how it could be implemented in pdepend.

**Comment by ravage84** [comment]
There are dedicated tools for LOC, such as the (nowadays deprecated) [PHPLOC](https://github.com/sebastianbergmann/phploc).

If this gets actually requested, we can re-evaluate butuntil then, let's close it.
