### ISSUE TITLE
PHP 7.4 features support

### ISSUE THREAD

**Issue by semalley** [pdepend/pdepend#456]
- PHP Depend version: 7.4.2
- PHP Version: 7.4.2
- Package Verison:  "2.7.0"
- Installation type: composer
- Operating System / Distribution & Version: Linux 4.19.76

### Current Behavior
phpmd failed with usage php 7.4 features

### Expected Behavior
To be fixed for [phpmd](https://github.com/phpmd/phpmd/issues/731)

**Comment by kylekatarnls** [comment]
Please try to require `"pdepend/pdepend": "dev-master"`

The next version will include this fix:
https://github.com/pdepend/pdepend/pull/455

**Comment by semalley** [comment]
@kylekatarnls Thanks it works for me.
