### ISSUE TITLE
file cache ttl

### ISSUE THREAD

**Issue by sveneld** [pdepend/pdepend#465]
## Description
Allow to configure file cache ttl in configuration file.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] Tell if you have the option to provide the code for this proposal.
* [x] This issue is about 1 feature proposal and nothing more.
* [x] The issue has a descriptive title. For example: "Support nullable types".

**Comment by tvbeek** [comment]
@sveneld Thanks for creating the issue and PR for this nice addition. It is merged in master and will be part of the next release.
