### ISSUE TITLE
Add missing PHP 8 tokens

### ISSUE THREAD

**Issue by T2L** [pdepend/pdepend#491]
## Description
Allow PDepend and programs depending on it to run with PHP 8.

- [ ] Add missing PHP 8 tokens

This issue enables the library to run, [see php8.0 issues for syntax support](https://github.com/pdepend/pdepend/labels/php8.0)

**Comment by kylekatarnls** [comment]
This is actually not a single feature proposal and for from being an easy upgrade. It's yet discussed internally and each PHP 8 feature needs to be implemented on its own:

- Named arguments
- Attributes
- Constructor property promotion
- Union types
- Match expression
- Nullsafe operator

https://www.php.net/releases/8.0/en.php?lang=en

**Comment by T2L** [comment]
hi @kylekatarnls, thanks for the response. Yep, seems like a lot of work. 

Have you considered making it running on PHP8 first and then being able to parse PHP8 code? Does it make any sense?

**Comment by kylekatarnls** [comment]
Problem preventing to run PDepend on PHP 8 is identified (missing tokens), if there are other issues I'll add it there. And I will create other issues for the syntax support.

**Comment by T2L** [comment]
Great! 

BC-breaking change in tokenization is described here: https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.tokenizer

**Comment by kylekatarnls** [comment]
PHP 8 support advancement can now be followed in a more detailed view using [PHP 8.0 label](https://github.com/pdepend/pdepend/labels/php8.0) so I close this issue.
