### ISSUE TITLE
Support PHP 8 Attributes

### ISSUE THREAD

**Issue by kylekatarnls** [pdepend/pdepend#493]
## Description

Support PHP 8 Attributes

```php
class PostsController
{
    #[Route("/api/posts/{id}", methods: ["GET"])]
    public function get($id) { /* ... */ }
}
```

https://www.php.net/releases/8.0/en.php?lang=en#attributes

**Comment by tvbeek** [comment]
Is there something that need to be done with this? (Is there any code that does something with comments that I forget?)

**Comment by kylekatarnls** [comment]
See the full spec:
https://wiki.php.net/rfc/attributes_v2

And code:
https://github.com/php/php-src/pull/5394/files#diff-487aa04101b106577c76d4f7f97cb3b841dd4471133f275538c04f812b937be5R6
