### ISSUE TITLE
Support PHP 8 Constructor property promotion

### ISSUE THREAD

**Issue by kylekatarnls** [pdepend/pdepend#494]
## Description

Support PHP 8 Constructor property promotion

```php
class Point {
  public function __construct(
    public float $x = 0.0,
    public float $y = 0.0,
    public float $z = 0.0,
  ) {}
}
```

https://www.php.net/releases/8.0/en.php?lang=en#constructor-property-promotion

**Comment by garak** [comment]
I think you should re-open this issue, because phpmd is failing whenever promoted property has a comment before:
```php
// this will cause "Unexpected token: private" error because of comment before `$x` declaration
class Point {
  public function __construct(
    // a comment here...
    public float $x = 0.0,
    public float $y = 0.0,
    public float $z = 0.0,
  ) {}
}
```
The same problem exists for multi-line comments (e.g. using `/* ... */`).

Tested with PHPMD 2.10.1snapshot202105111723

**Comment by kylekatarnls** [comment]
Indeed, I guess, this is also the same issue for attributes before property promotion: https://github.com/phpmd/phpmd/issues/899

**Comment by kylekatarnls** [comment]
Hello @garak can you reproduced with `"pdepend/pdepend": "dev-master"` installed?

I added unit tests and tried various comment styles and positions (including the exact code chunk you gave) but was not able to reproduce your issue.

Tried also your code with PHPMD with pdepend dev-master installed and it sounds to be fixed already. Please check #549 and add a test if you're still able to reproduce the bug with the last version.

**Comment by anaurias** [comment]
**Avoid unused parameters such** as problem also happens constructor promotion? Has anyone had this problem?

**Comment by gpayo** [comment]
@anaurias Yup, me. If I declare the private variable as non-promoted, the error disappear.

**Comment by anaurias** [comment]
> @anaurias Yup, me. If I declare the private variable as non-promoted, the error disappear.

@gpayo is this behavior correct?

**Comment by kylekatarnls** [comment]
Hello people, I re-opened the ticket https://github.com/phpmd/phpmd/issues/884 to track this. As this is likely no longer an issue from PDepend side (promotion is detected and flagged) but from how PHPMD sees it's used or not.

**Comment by kylekatarnls** [comment]
Also please try to install `"pdepend/pdepend": "dev-master"` and `"phpmd/phpmd": "dev-master"` to see if you case is already solved by the next release, else please provide your exact code so we can reproduce it and include it in our test cases.
