### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by mre** [pdepend/pdepend#504]
The website currently returns a 404 for me. I can't find the bug right now. At least all necessary files seem to be in the [gh-pages](https://github.com/pdepend/pdepend/tree/gh-pages) branch. My best guess is that it's somehow related to the [migration to Github actions](https://github.com/pdepend/pdepend/commit/02df750fa20689df142885c1ea949e5cbc004bf3).

**Comment by kylekatarnls** [comment]
Yes, thanks, it's handled in #503
