### ISSUE TITLE
Support PHP 8 static return type

### ISSUE THREAD

**Issue by Shyryuu** [pdepend/pdepend#518]
In PHP 8 it is possible to declare _static_ as the return type of a function. e.g:

```php
<?php

class Test
{
    public static function create() : static
    {
        return new static();
    }
}
```

Running pdepend against this file produces the following output:

```
Processing file /test/src/Test.php
Creating: \PDepend\Source\AST\ASTMethod(create)
Creating: \PDepend\Source\AST\ASTFormalParameters()
Fatal error: Uncaught TypeError: PDepend\Source\AST\AbstractASTCallable::addChild(): Argument #1 ($node) must be of type PDepend\Source\AST\ASTNode, null given, called in /test/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php on line 184 and defined in /test/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTCallable.php:143
Stack trace:
#0 /test/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(184): PDepend\Source\AST\AbstractASTCallable->addChild(NULL)
#1 /test/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1274): PDepend\Source\Language\PHP\PHPParserVersion70->parseCallableDeclarationAddition(Object(PDepend\Source\AST\ASTMethod))
#2 /test/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1231): PDepend\Source\Language\PHP\AbstractPHPParser->parseCallableDeclaration(Object(PDepend\Source\AST\ASTMethod))
#3 /test/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(988): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodDeclaration()
#4 /test/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php(87): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration(17)
#5 /test/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(887): PDepend\Source\Language\PHP\PHPParserVersion74->parseMethodOrFieldDeclaration(1)
#6 /test/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(723): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody(Object(PDepend\Source\AST\ASTClass))
#7 /test/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6055): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
#8 /test/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(397): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#9 /test/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(587): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#10 /test/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(335): PDepend\Engine->performParseProcess()
#11 /test/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Runner.php(314): PDepend\Engine->analyze()
#12 /test/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Command.php(243): PDepend\TextUI\Runner->run()
#13 /test/vendor/pdepend/pdepend/src/main/php/PDepend/TextUI/Command.php(627): PDepend\TextUI\Command->run()
#14 /test/vendor/pdepend/pdepend/src/bin/pdepend(72): PDepend\TextUI\Command::main()
#15 {main}
  thrown in /test/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTCallable.php on line 143
```

**Comment by kylerqws** [comment]
When is the fix planne?
I have the same problem. Developing in PHP 8 without support for the "static" return value is quite sad.

**Comment by tvbeek** [comment]
@kylerqws the beauty of open source is that everybody can contribute 😃 And if someone want to fix this and need some support he/she can ask for help.

It is fixed if someone (it can be a maintainer but that isn't needed) provide a pull request with a fix. And yes we have currently some open issues for PHP 8 that need to be handled, see: https://github.com/pdepend/pdepend/labels/php8.x

Do you have the option to fix this?

**Comment by kylerqws** [comment]
@tvbeek Yes, I know how to fix this error and would like to help with it. I have never had any experience of participating in the development of an open source project, I can not find the CONTRIBUTING.md file, tell me where to start?

**Comment by tvbeek** [comment]
@kylerqws about CONTRIBUTING.md that is a good point, I created an issue about it, see: https://github.com/pdepend/pdepend/issues/523

To get started: we have the parsers in https://github.com/pdepend/pdepend/tree/master/src/main/php/PDepend/Source/Language/PHP each PHP version has a parser that has the changes comparing with the previous version.

We should like a PR with tests, they suspect a resource to parse with a result. I think the most easy point to start is looking to another PR like: https://github.com/pdepend/pdepend/pull/508/files

You can start a draft PR, on that way it is clear that it isn't finished yet but you like some feedback or help from other people. It is also possible to talk on gitter: https://gitter.im/pdepend/community (we aren't continues online but can answer while we are online)

**Comment by kylerqws** [comment]
@tvbeek How do I get the permissions to create PR?

**Comment by kylekatarnls** [comment]
Hello, 👋  there is no permissions required to create a pull-request, with your GitHub account you can freely propose pull-request to any active project you can find on GitHub. Here is a [guide for fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks)

Basically, you click the [Fork] button (top-right corner) to create your own copy of pdepend: it will create https://github.com/kylerqws/pdepend those you can clone locally pull/push branches and commits as any repository you would have created yourself.

Then when the branch has the changes you want and work as you expect, you can push it, then clicking on [New pull request](https://github.com/pdepend/pdepend/compare) you can find your fork (compare across fork) and submit your changes.

**Comment by kylerqws** [comment]
There is no time to implement tests now. By analogy with previous versions of php, integer is returned in the test, but I have not yet understood what it means.

**Comment by kylekatarnls** [comment]
Hello @kylerqws code looks good. I will add the unit test.

**Comment by kylekatarnls** [comment]
Planned for 2.9.1.
