### ISSUE TITLE
Error on trailing comma in group use declarations

### ISSUE THREAD

**Issue by JKapitein** [pdepend/pdepend#519]
- PHP Depend version: 2.9.0
- PHP Version: 7.0+
- Installation type: composer
- Operating System / Distribution & Version: Ubuntu 16.04.7 LTS

### Current Behavior
In PHPParserVersion70::parseUseDeclarationVersion70 it does not support trailing commas in a grouped use block. This is allowed according to the [RFC](https://wiki.php.net/rfc/group_use_declarations) for group use declarations, but currently any grouped use declaration that has a trailing comma will generate an "Unexpected token: }" error during parsing.

### Expected Behavior
Parsing of the grouped use ends and parsing of the file continues normally when a comma is followed by a } in a grouped use block.

### Steps To Reproduce:
File test.php
```
<?php

namespace TestSpace;

class TestA {}
class TestB {}

namespace ErrorSpace;

use TestSpace\{TestA, TestB,};

class TestC {}
```

Command
`pdepend --summary-xml=/dev/null test.php`

## Checks before submitting
* [X] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [X] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [X] I have added every step to reproduce the bug.
* [X] If possible I added relevant code examples.
* [X] This issue is about 1 bug and nothing more.
* [X] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by tvbeek** [comment]
@JKapitein Thanks for reporting, I was first surprised that it was possible but indeed it is.

We are welcoming a PR to handle this.

**Comment by JKapitein** [comment]
@tvbeek I'm willing to try my hand at a pull request, and have a general idea about how to solve it, but I have zero experience with lexical parsing so you'll have to be patient with me ;)

In any case I'll see if I can make some time tomorrow.

**Comment by kylekatarnls** [comment]
🙏 Thank you so much. Maybe I can try to find other places where we dealt before with trailing commas (array likely).
