### ISSUE TITLE
I can't download "pdepend.phar" - unknown host static.pdepend.org

### ISSUE THREAD

**Issue by SmetDenis** [pdepend/pdepend#521]
- PHP Depend version: 2.9.0
- PHP Version: any
- Installation type: phar file
- Operating System / Distribution & Version: Ubuntu, Mac OS

### Current Behavior
According to [docs](https://pdepend.org/download/index.html) I can't download phar file.

### Expected Behavior
Phar file is downloaded via curl/wget.

### Steps To Reproduce:
I tried to download the file via `wget  http://static.pdepend.org/php/latest/pdepend.phar` on different hosts.

```sh
$ wget  http://static.pdepend.org/php/latest/pdepend.phar
--2021-03-29 18:12:48--  http://static.pdepend.org/php/latest/pdepend.phar
Resolving static.pdepend.org (static.pdepend.org)... failed: Name or service not known.
wget: unable to resolve host address ‘static.pdepend.org’
```

Ping also doesn't see the host
```sh
$ ping static.pdepend.org
ping: static.pdepend.org: Name or service not known
```

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by tvbeek** [comment]
@SmetDenis Thanks for reporting, we should have a download on the website so we need to fix it. You can also download it from the releases see: https://github.com/pdepend/pdepend/releases so I hope that it can help you for this moment.

**Comment by SmetDenis** [comment]
@tvbeek Ok. Good to know. Thanks.
I guess the website page has to be updated as well.

You know, it's nice to have a direct link to the latest stable version, like `latest/pdepend.phar` :)

**Comment by tvbeek** [comment]
> 
> 
> @tvbeek Ok. Good to know. Thanks.
> I guess the website page has to be updated as well.
> 
> You know, it's nice to have a direct link to the latest stable version, like `latest/pdepend.phar` :)

Totally true 😃

**Comment by SmetDenis** [comment]
@tvbeek  I'm so sorry.
I can't find a phar file on the release page  - https://github.com/pdepend/pdepend/releases/tag/2.9.0
I expected to see it in "Assets" as an attachment :(

**Comment by tvbeek** [comment]
@SmetDenis you don't need to be sorry, you are good in finding en reporting problems. And maybe this is the root problem.

I see that there is a phar for the 2.8.0 release: https://github.com/pdepend/pdepend/releases/tag/2.8.0

**Comment by kylekatarnls** [comment]
It was automatically added via Travis in 2.8.0, indeed with GitHub Actions, we now have to rework on that. I'll add it manually.

**Comment by kylekatarnls** [comment]
Added https://github.com/pdepend/pdepend/releases/download/2.9.0/pdepend.phar

**Comment by kylekatarnls** [comment]
Side note, the phar generated automatically for any commit can now be downloaded via GitHub Actions:
https://github.com/pdepend/pdepend/actions/workflows/phar.yml

**Comment by SmetDenis** [comment]
Awesome. Thank you so much!

**Comment by kylekatarnls** [comment]
Thanks to @tvbeek the new URL is up:
https://pdepend.org/static/latest/pdepend.phar
