### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: PDepend\Source\AST\AbstractASTNode::addChild(): Argument #1 ($node) must be of type PDepend\Source\AST\ASTNode, null given

### ISSUE THREAD

**Issue by andrei-vdc** [pdepend/pdepend#522]
- PHP Depend version: 2.9.0
- PHP Version: 8.0.3
- Installation type: (composer)
- Operating System / Distribution & Version: (Ubuntu 20.4)

### Current Behavior
```
PHP Fatal error:  Uncaught TypeError: PDepend\Source\AST\AbstractASTNode::addChild(): Argument #1 ($node) must be of type PDepend\Source\AST\ASTNode, null given, called in /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php on line 271 and defined in /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTNode.php:369
Stack trace:
#0 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php(271): PDepend\Source\AST\AbstractASTNode->addChild()
#1 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(207): PDepend\Source\Language\PHP\PHPParserVersion80->parseTypeHint()
#2 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php(92): PDepend\Source\Language\PHP\PHPParserVersion70->parseReturnTypeHint()
#3 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(183): PDepend\Source\Language\PHP\PHPParserVersion71->parseReturnTypeHint()
#4 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1274): PDepend\Source\Language\PHP\PHPParserVersion70->parseCallableDeclarationAddition()
#5 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1231): PDepend\Source\Language\PHP\AbstractPHPParser->parseCallableDeclaration()
#6 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(988): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodDeclaration()
#7 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php(87): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration()
#8 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(887): PDepend\Source\Language\PHP\PHPParserVersion74->parseMethodOrFieldDeclaration()
#9 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(662): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody()
#10 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6045): PDepend\Source\Language\PHP\AbstractPHPParser->parseInterfaceDeclaration()
#11 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(397): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#12 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(587): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#13 /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(335): PDepend\Engine->performParseProcess()
#14 /var/www/KnitAndNote/backend/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(95): PDepend\Engine->analyze()
#15 /var/www/KnitAndNote/backend/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(192): PHPMD\Parser->parse()
#16 /var/www/KnitAndNote/backend/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(103): PHPMD\PHPMD->processFiles()
#17 /var/www/KnitAndNote/backend/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(148): PHPMD\TextUI\Command->run()
#18 /var/www/KnitAndNote/backend/vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main()
#19 {main}
  thrown in /var/www/KnitAndNote/backend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTNode.php on line 369
```

### Expected Behavior
No Fatal Errors.

### Steps To Reproduce:
- composer require phpmd/phpmd:~2.9 (pdepend/pdepend) is a dependency of phpmd
- run `vendor/bin/phpmd app/ xml phpmd.xml`

**Comment by tvbeek** [comment]
@andrei-vdc can you share some code that result in this error? Maybe it is some of the open tickets for PHP 8, see: https://github.com/pdepend/pdepend/issues?q=is%3Aissue+is%3Aopen+label%3Aphp8.x but without more information we can't tell what result in this error.

**Comment by NeilMasters** [comment]
PHPParserVersion80:255

`protected function parseTypeHint()
    {
        $types = array(parent::parseTypeHint());

        while ($this->tokenizer->peek() === Tokens::T_BITWISE_OR) {
            $this->tokenizer->next();
            $types[] = parent::parseTypeHint();
        }

        if (count($types) === 1) {
            return $types[0];
        }

        $unionType = $this->builder->buildAstUnionType();

        var_dump($types);
        exit;
        foreach ($types as $type) {
            $unionType->addChild($type);
        }

        return $unionType;
    }`

That var dump highlights:

`array(4) {
  [0]=>
  object(PDepend\Source\AST\ASTScalarType)#4041 (4) {
    ["nodes":protected]=>
    array(0) {
    }
    ["parent":protected]=>
    NULL
    ["comment":protected]=>
    NULL
    ["metadata":protected]=>
    string(10) "::::string"
  }
  [1]=>
  object(PDepend\Source\AST\ASTScalarType)#4042 (4) {
    ["nodes":protected]=>
    array(0) {
    }
    ["parent":protected]=>
    NULL
    ["comment":protected]=>
    NULL
    ["metadata":protected]=>
    string(7) "::::int"
  }
  [2]=>
  object(PDepend\Source\AST\ASTScalarType)#4043 (4) {
    ["nodes":protected]=>
    array(0) {
    }
    ["parent":protected]=>
    NULL
    ["comment":protected]=>
    NULL
    ["metadata":protected]=>
    string(9) "::::float"
  }
  [3]=>
  NULL
}`

That last null value then gets chucked into the below method which is type hinted to not be nullable.

`/**
     * This method adds a new child node to this node instance.
     *
     * @param \PDepend\Source\AST\ASTNode $node
     * @return void
     */
    public function addChild(ASTNode $node)
    {
        $this->nodes[] = $node;
        $node->setParent($this);
    }`

**Comment by NeilMasters** [comment]
@tvbeek @andrei-vdc See my notes from above.

This is caused by union type hinting _with_ null. I.e.

public function foobar(string | int | null) {}

Remove that null value and the issue goes away.

**Comment by kylekatarnls** [comment]
Nice job. Thanks for the debugging. I think I can fix this.
