### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in phar:///.../bin/phpmd-extension.phar/vendor/pdepend/pdepend/src/main/php/PDepen d/Metrics/Analyzer/InheritanceAnalyzer.php:204

### ISSUE THREAD

**Issue by vpassapera** [pdepend/pdepend#539]
- PHP Depend version: 2.9.1
- PHP Version: 8.0
- Installation type: phar
- Operating System / Distribution & Version: Docker / Alpine

### Current Behavior
Whenever the pipe operator is used in return hints for methods, error happens.
Whenever a named parameter is used, error happens.

### Expected Behavior
No error for PHP syntax.

### Steps To Reproduce:
Have a method defined that returns as an example (In real code this would be a collection | iterable:

```
public function foo(): iterable | array
{
   return [];
}
```

## Checks before submitting

* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by vpassapera** [comment]
Closing as duplicate of #532

**Comment by tvbeek** [comment]
Thanks for reporting, this indeed looks like a bug in PHP Depend.

Small question: do you have the option to create a PR? If not with a fix maybe with a failing test for this code? Else someone else will do it if he/she has the time.

**Comment by kylekatarnls** [comment]
Hello, a fix is in progress, you can try it with:

```
composer require pdepend/pdepend:dev-fix/union-types
```

**Comment by vpassapera** [comment]
@kylekatarnls Just noticed these responses. Thank you!

Will test it out.
