### ISSUE TITLE
Link Software Metrics is wrong

### ISSUE THREAD

**Issue by fgsl** [pdepend/pdepend#557]
## Description
Hyperlink Software Metrics into page https://pdepend.org/documentation/getting-started.html is wrong. It points to http://clarkware.com/software/JDepend.html.

**How to fix:**

Replace href attribute to https://pdepend.org/documentation/software-metrics/index.html.

**Comment by kylekatarnls** [comment]
Hello, where do you see this link?

If you refer PHPDoc of `PDepend\Engine` or `PDepend\Report\Jdepend\Xml` those are reference to the original idea, so this is not meant to provide a documentation link but to mention original project.

Links to the list of the metrics could be added in some relevant places for documentation purpose, but I don't think we should remove the link to https://github.com/clarkware/jdepend

**Comment by fgsl** [comment]
Hi, @kylekatarnls. The link is at the bottom of this page: https://pdepend.org/documentation/getting-started.html 

![image](https://user-images.githubusercontent.com/128915/133912361-a9e2a36e-0cd8-424f-9f83-8699a82b6ff4.png)

**Comment by kylekatarnls** [comment]
Ah correct, this one must be fixed.
