### ISSUE TITLE
Php 8 named arguments when argument named 'default'

### ISSUE THREAD

**Issue by archfz** [pdepend/pdepend#559]
- PHP Depend version: 2.x-dev
- PHP Version: 8.0.3
- Installation type: composer
- Operating System / Distribution & Version: (Windows 10 / CentOS 7.6 / ...)

### Current Behavior
This fails to be parsed, but it's correct php syntax.

```php
new FinanceProduct(
                    id: new FinanceProductId($result->getId()),
                    label: $result->getLabel(),
                    order: $result->getOrder(),
                    default: $result->isDefault(),
                    financePackageCollection: $this->getPackages($result->getFinancePackageCollection())
                )
```

Gives error
```text
Unexpected token: default, line: 53, col: 21, file: /app/src/Infrastructure/FinanceCalculator/FinanceProductRepository/FinanceProductRepository.php.
```

### Expected Behavior
Do not fail.

### Steps To Reproduce:
Above.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by kylekatarnls** [comment]
I tested and this apply to any keyword: `if`, `class`, `as` (everyone of the 55 possible PHP keywords).

Actually this is related to a PHP bug, the native `token_get_all()` returns irrelevant token for argument name when it matches a keyword:

```php
$tokens = token_get_all("<?php biz(switch: 'bar');");

foreach ($tokens as $token) {
    if ((((array) $token)[1] ?? null) === 'switch') {
        echo token_name($token[0]);

        break;
    }
}
```

We should legitimately get `T_STRING` (e.g. what we get with any other variable name) as there is no way it can actually be a `switch` or any kind of structure in this sequence.

We can work around this by checking in each argument if second token is ":" and first token has an image that contains only letters.

You can test it using:
```
composer require pedpend/pdepend:dev-fix/default-argument-name --dev
```

**Comment by archfz** [comment]
Confirmed working.
