### ISSUE TITLE
Fatal error if no return type after colon

### ISSUE THREAD

**Issue by przepompownia** [pdepend/pdepend#634]
- phpmd version: dev-master 79c937c
- PHP Depend version: dev-master 4870c10
- PHP Version: 8.1.10
- Installation type: composer
- Operating System / Distribution & Version: Debian Sid

### Current Behavior
```
PHP Fatal error:  Uncaught TypeError: PDepend\Source\AST\AbstractASTCallable::addChild(): Argument #1 ($node) must be of type PDepend\Source\AST\ASTNode, null given, called in /home/arctgx/.composer/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php on line 204 and defined in /home/arctgx/.composer/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTCallable.php:153
```

### Expected Behavior
No fatal error

### Steps To Reproduce:
- In `src/Foo.php` nside a class create a method without return type after colon in its declaration:
```php
<?php

class Foo
{
    public function name():
    {
    }
}
```
- run `phpmd src/Foo.php text cleancode`

The example comes from my snippet. I can put some type as the default but this error should not happen independently of that.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by kylekatarnls** [comment]
Hello, when code contains a syntax error, whatever it is, we can't guarentee to fallback, and anyway most of the time it would be harmfull, I highly recommend to use a `php -l` to check PHP syntax first.

**Comment by tvbeek** [comment]
@przepompownia Supporting files with syntax errors is out of scope for PDepend, it will require a guess about what to do with it. If you have a clear way to handle syntax errors we can discuss a PR with the changes. But for now I will close this issue.

**Comment by przepompownia** [comment]
@tvbeek At the moment it's enough for me if I'll configure my IDE part (currently it's null-ls) to not run `phpmd` iff `php` detected syntax error before. 

Thanks for clear responses.
