### ISSUE TITLE
Enum with DEFAULT or NEW case result in error.

### ISSUE THREAD

**Issue by tvbeek** [pdepend/pdepend#635]
- PHP Depend version: 2.12.1
- PHP Version: 8.1.7
- Installation type: composer (with PHPMD)
- Operating System / Distribution & Version: Alpine 3.16 (docker container)

### Current Behavior
When an enum contains a value named `DEFAULT` or `NEW`, pdepend crashes.

### Expected Behavior
Expected behavior is no error, just a successful analysis.

### Steps To Reproduce:
Create a class with the enum and run PDepend on it

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

This is first reported in: https://github.com/phpmd/phpmd/issues/985

**Comment by guvra** [comment]
Note: it happens with any PHP keyword (e.g. "CLASS", "INTERFACE"...) and is case insensitive (e.g. "CLASS", "Class", "class" all result in a fatal error).

**Comment by ericfortmeyer** [comment]
The error also occurs when the enum's member is named Null.

**Comment by tvbeek** [comment]
> Note: it happens with any PHP keyword (e.g. "CLASS", "INTERFACE"...) and is case insensitive (e.g. "CLASS", "Class", "class" all result in a fatal error).
> 
> Example test file (test.php):
> 
> ```
> <?php
> 
> enum Test
> {
>     case CLASS;
> }
> ```

```
php -l test.php
Result in: PHP Fatal error:  A class constant must not be called 'class'; it is reserved for class name fetching in test.php on line 4
Error parsing test.php
```

That means class isn't allowed.

This are valid names for constants but not yet handled by PDepend.
* DEFAULT
* NEW
* NULL

**Comment by florianajir** [comment]
I got the same error for enum name `DEFAULT` and `CONTINUE` also

**Comment by natanfelles** [comment]
Same for `parent`.
