### ISSUE TITLE
Unexpected Token Exception for class name is thrown when using combination "readonly" and "final" or "readonly" and "abstract"

### ISSUE THREAD

**Issue by EmilPDev** [pdepend/pdepend#638]
- PHP Depend version: 2.12.1
- PHP Version: 8.2.0
- Installation type: composer
- Operating System / Distribution & Version: Docker image webdevops/php-nginx-dev
- phpmd/phpmd 2.13.0

### Current Behavior
Unexpected Token Exception for class name is thrown when using combination "readonly" and "final" or "readonly" and "abstract".

### Expected Behavior
The same behavior as when you use the words separately.

### Steps To Reproduce:
1. Use combination of words "readonly" and "final" for declaration of class e.g. "final readonly class SmsStatusChecker" or "readonly final class SmsStatusChecker" or "abstract readonly class AbstractStringValueObject implements Stringable",...
2. Run PHPMD command

Error log:
 Unexpected token: readonly, line: 22, col: 7, file: /app/app/Service/SmsStatusChecker.php.
#0 /app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7965): PDepend\Source\Parser\UnexpectedTokenException->__construct(Object(PDepend\Source\Tokenizer\Token), Object(PDepend\Source\AST\ASTCompilationUnit))

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by tvbeek** [comment]
Example with code and stack trace:

```php
<?php
final readonly class SmsStatusChecker
{

}
```

Stack trace
```log
        -       Unexpected token: readonly, line: 3, col: 7, file: /home/tjvb/projects/phpmd/test.php.
#0 /home/tjvb/projects/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7966): PDepend\Source\Parser\UnexpectedTokenException->__construct()
#1 /home/tjvb/projects/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7933): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
#2 /home/tjvb/projects/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(885): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken()
#3 /home/tjvb/projects/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(862): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassSignature()
#4 /home/tjvb/projects/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6643): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
#5 /home/tjvb/projects/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(516): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#6 /home/tjvb/projects/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(606): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#7 /home/tjvb/projects/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(351): PDepend\Engine->performParseProcess()
#8 /home/tjvb/projects/phpmd/src/main/php/PHPMD/Parser.php(99): PDepend\Engine->analyze()
#9 /home/tjvb/projects/phpmd/src/main/php/PHPMD/PHPMD.php(240): PHPMD\Parser->parse()
#10 /home/tjvb/projects/phpmd/src/main/php/PHPMD/TextUI/Command.php(136): PHPMD\PHPMD->processFiles()
#11 /home/tjvb/projects/phpmd/src/main/php/PHPMD/TextUI/Command.php(184): PHPMD\TextUI\Command->run()
#12 /home/tjvb/projects/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main()
#13 {main}
```

**Comment by Hikariii** [comment]
@tvbeek and @EmilPDev, I just added a PR to fix this https://github.com/pdepend/pdepend/pull/642
