### ISSUE TITLE
PDEPEND does not allow public/protected/private keys within enum.

### ISSUE THREAD

**Issue by TheCelavi** [pdepend/pdepend#640]
- PHP Depend version: 2.12.1
- PHP Version: 8.2
- Installation type: composer
- Operating System / Distribution & Version: MacOS X Ventura, using Docker, Debian

### Current Behavior

This is valid PHP enum:

```
enum Access
{
    case PUBLIC;
    case PROTECTED;
}
```

Yields error: Unexpected token: PUBLIC, line: 17, col: 10, file: /var/www/html/src/Contract/Subscription/Registry/Access.php.

### Expected Behavior
No errors.

### Steps To Reproduce:
Add above mentioned enum and run analysis.

**Comment by dimitriBouteille** [comment]
Probably same bug : https://github.com/pdepend/pdepend/issues/650

**Comment by tvbeek** [comment]
I just verified it with the latest development version and it is indeed fixed with #656
