### ISSUE TITLE
PDepend 2.13.0 is missing a phar download

### ISSUE THREAD

**Issue by SMillerDev** [pdepend/pdepend#659]
- PHP Depend version: 2.13.0
- PHP Version: 8.2.x
- Installation type: phar file
- CentOS 7.6

### Current Behavior
https://github.com/pdepend/pdepend/releases/tag/2.13.0 does not offer a phar download

### Expected Behavior
https://github.com/pdepend/pdepend/releases/tag/2.13.0 should offer a phar download like earlier versions

### Steps To Reproduce:
Open https://github.com/pdepend/pdepend/releases/tag/2.13.0

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by tvbeek** [comment]
Hello @SMillerDev 

Thanks for reporting, I have added the .phar file.

**Comment by SMillerDev** [comment]
Thanks @tvbeek !
