### ISSUE TITLE
Unexpected token when using promoted properties with two modifiers in constructor

### ISSUE THREAD

**Issue by Allemweich** [pdepend/pdepend#665]
- PHP Depend version: 2.13.0
- PHP Version: 8.1.
- Installation type: composer
- Operating System / Distribution & Version: Ubuntu 20.04

### Current Behavior
```php
class TimeSwitchPeriod
{
    public function __construct(
        readonly public string $weekDays,
        readonly public string $times
    ) {
    }
}
```

This class is valid PHP as of 8.1, using constructor property promotion and the readonly modifier.
When running PHPMD with pdepend:2.13.0, I get this error:

**Unexpected token: public, line: 8, col: 18, file: <redacted>/TimeSwitchPeriod.php**

### Expected Behavior
No error is raised.

### Steps To Reproduce:
- Copy the class above, or any that uses a promoted property with two modifiers (e.g. `readonly public`) in the constructor
- Run PHPMD
- Get the unexpected token error

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by Allemweich** [comment]
Nevermind... The correct syntax is `public readonly`.

**Comment by takaram** [comment]
No, the order of modifiers doesn't matter in PHP. `readonly public` is a valid syntax too.
https://3v4l.org/Q1OqI

So this issue should be reopened.
