### ISSUE TITLE
Critical Error: A compilation unit should contain at least one token

### ISSUE THREAD

**Issue by andrey-tech** [pdepend/pdepend#682]
- PHP Depend version: 2.15.0
- PHP Version: 7.4.33
- Installation type: composer
- Operating System / Distribution & Version: GNU/Linux Ubuntu 5.15.0-83-generic x86_64

### Current Behavior
Critical error while "parsing source files": 
```
Critical error:
===============
A compilation unit should contain at least one token
```
### Expected Behavior
No errors while parsing source files (version 2.14.0).

### Steps To Reproduce:

```sh
vendor/bin/pdepend --summary-xml=./summary.xml src
```

## Checks before submitting
* [✓ ] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [✓ ] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [✓ ] I have added every step to reproduce the bug.
* [✓ ] If possible I added relevant code examples.
* [✓ ] This issue is about 1 bug and nothing more.
* [ ✓] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by tvbeek** [comment]
Hello @andrey-tech 

First of all, thanks for your report.

Can you provide more information about the code that you scan? Maybe the ---debug flag can help to see where it result in this error.

I have tried it on my own code and I can't reproduce it, so a specific code part can help to find and fix this problem.

**Comment by andrey-tech** [comment]
Hello @tvbeek 

An absolutely empty file with extension `.php` causes this critical error.

**Comment by kylekatarnls** [comment]
Hello,

I confirm this is the current behavior. It also happen when scanning a folder as soon as the folder contains 1 empty files even if it also contains non-empty files.

Having an error when no token at all is scanned might be helpful for users to find out that they might not scan the right target. 

However I think we should not raise it as soon as the path list contain at least 1 non-empty file.
