### ISSUE TITLE
Typo in encoding name

### ISSUE THREAD

**Issue by snarktooth** [pdepend/pdepend#688]
I've been seeing this error repeated many times when running pdepend on my project: `[PHP Error] iconv(): Wrong encoding, conversion from "ASCII" to "UTF8//IGNORE" is not allowed [line 74 of phar:///mnt/tools/phing/vendor/pdepend/pdepend/src/main/php/PDepend/Util/Utf8Util.php]`

After an embarrassingly long bit of head scratching, I finally realized that the similar call to `iconv` five lines later specifies `UTF-8//IGNORE` instead of `UTF8//IGNORE`.
https://github.com/pdepend/pdepend/blob/bfb52ab6410d1d06a4162be9fc3a3e3a93233166/src/main/php/PDepend/Util/Utf8Util.php#L74

**Comment by snarktooth** [comment]
Sorry for not replying earlier; I was racing the clock to track down the source of the warnings and open the issue before leaving town for a week.  I can confirm that the fix now in master works for me.  For the curious, I'm using phing to execute pdepend, which must be capturing the warnings that we would expect to be suppressed by the @.  That's running inside a docker container based on the official php:8.2-alpine image.  I did some testing with iconv and it appears Alpine (with libiconv) is pickier about the "UTF-8" name than a Fedora 38 environment (with glibc) which accepts "UTF8" without complaint.

In any case, thanks for the fix.

**Comment by AJenbo** [comment]
Alpines iconv is indeed much more limited then other distros.
