### ISSUE TITLE
Invalid characters passed to "octdec"

### ISSUE THREAD

**Issue by r-man** [pdepend/pdepend#690]
- PHP Depend version: 2.15.1
- PHP Version: 8.2.8
- Installation type: composer
- Operating System / Distribution & Version: Ubuntu 23.10

### Current Behavior
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /var/www/html/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 8219

### Expected Behavior
No deprecation messages.

### Steps To Reproduce:
0) You need to enable E_DEPRECATED in the error_reporting directive.
1) Create PaymentDTO.php
````
class PaymentDTO
{
    private float $amount = 0.00;
}
````
2) Run
````
vendor/bin/pdepend --summary-xml=summary.xml PaymentDTO.php
````

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by kylekatarnls** [comment]
Bug confirmed, I should be able to provide a fix quickly.
