### ISSUE TITLE
Compatibility Issue with Symfony/Config v7.0.0 in `getConfigTreeBuilder` Method

### ISSUE THREAD

**Issue by leodisarli** [pdepend/pdepend#695]
**Title**: Compatibility Issue with Symfony/Config v7.0.0 in `getConfigTreeBuilder` Method

**Environment**:
- PHP Depend version: 2.16.0
- PHP Version: 8.3.0
- Symfony/Config version: v7.0.0 (laravel/lumen-framework v10.0.2, i've tried v10.0.1 and v10.0.0 also)
- Installation type: Composer
- Operating System: Ubuntu 18.04 (Official PHP Image php:8.3-rc-fpm)

### Issue Description
There's a compatibility issue with Symfony/Config version v7.0.0 in PDepend's `getConfigTreeBuilder` method. The current implementation in `src/main/php/PDepend/DependencyInjection/Configuration.php` does not match Symfony's expected structure, resulting in a fatal error like this:

```sh
Fatal error: Declaration of PDepend\DependencyInjection\Configuration::getConfigTreeBuilder() must be compatible with Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder(): Symfony\Component\Config\Definition\Builder\TreeBuilder in /var/www/html/vendor/pdepend/pdepend/src/main/php/PDepend/DependencyInjection/Configuration.php on line 77
```

The error message indicates a mismatch in the method declaration compared to the expected Symfony interface.

### Expected Behavior
To resolve this issue, I suggest to update the `getConfigTreeBuilder` method to align with Symfony's latest implementation, as sample bellow.

**Proposed Solution**:
```php
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
...
public function getConfigTreeBuilder() : TreeBuilder
{
    ...
    // replace line 84 
    $treeBuilder = new TreeBuilder('phpmd'); // here i don't go deep to understand the alias param, all my tests run succeffuly with a random string
    ...
    // replace line 109
    return $treeBuilder;
}
```

### Steps To Reproduce:
Install the dependencies and run the phpmd command to check the project like this
```sh
vendor/bin/phpmd ./app text phpmd.xml
```

### Composer Json
To help with the reproduce here my full dependencies on composer.json, the full file is attached if helps
```json
    "require": {
        "php": "^8.3",
        "intouch/newrelic": "^2.0",
        "laravel/lumen-framework": "^10.0",
        "not-empty/jwt-manager-php-lib": "^7.0",
        "not-empty/request-service-php-lib": "^7.0",
        "not-empty/response-json-php-lib": "^7.0",
        "not-empty/ulid-php-lib": "^7.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.23",
        "mockery/mockery": "^1.6",
        "phpmd/phpmd": "^2.14",
        "phpunit/phpunit": "^9.6",
        "squizlabs/php_codesniffer": "^3.7"
    },
```
[composer.json](https://github.com/pdepend/pdepend/files/13501186/composer.json)

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by olliescase** [comment]
This seems to have a proposed fix here: #696 

Commenting so the issue and PR are connected

**Comment by leodisarli** [comment]
Thanks @olliescase, i'll use the workaround until waiting the proper fix.
Cheers!

**Comment by leodisarli** [comment]
> This seems to have a proposed fix here: #696
> 
> Commenting so the issue and PR are connected
> 
> Currently I have tested this in my project (pdepend is required by phpmd for me) by adding the following to my composer json:
> 
> ```json
>     "repositories": {
>         "pdepend/pdepend": {
>             "type": "package",
>             "package": {
>                 "name": "pdepend/pdepend",
>                 "version": "2.16.1",
>                 "source": {
>                     "type": "git",
>                     "url": "https://github.com/symfonyaml/pdepend.git",
>                     "reference": "patch-1"
>                 },
>                 "require": {
>                     "php": ">=5.3.7",
>                     "symfony/dependency-injection": "^2.3.0|^3|^4|^5|^6.0|^7.0",
>                     "symfony/filesystem": "^2.3.0|^3|^4|^5|^6.0|^7.0",
>                     "symfony/config": "^2.3.0|^3|^4|^5|^6.0|^7.0",
>                     "symfony/polyfill-mbstring": "^1.19"
>                 },
>                 "require-dev": {
>                     "phpunit/phpunit": "^4.8.36|^5.7.27",
>                     "squizlabs/php_codesniffer": "^2.0.0",
>                     "gregwar/rst": "^1.0",
>                     "easy-doc/easy-doc": "0.0.0|^1.2.3"
>                 },
>                 "autoload": {
>                     "psr-4": {
>                         "PDepend\\": "src/main/php/PDepend"
>                     }
>                 }
>             },
>             "comment": "TODO: Remove this once the next stable version of pdepend is released"
>         },
>     }
> ```
> 
> and then adding `"phpdepend/phpdepend": "2.16.1",` in the require section of the composer json.

Ohhh they removed the branch, :-1: making this workaroud not possible anymore.

**Comment by kylekatarnls** [comment]
As you can see in this code snippet:

```json
{
  "type": "git",
  "url": "https://github.com/symfonyaml/pdepend.git",
  "reference": "patch-1"
}
```
It's not taking pdepend from a trusted/stable source, the `symfonyaml` in this URL means it's provided by @symfonyaml who kindly worked on fix, and `patch-1` is the branch, this was a possible work-around, but as a general practice be careful about what you put in your dependencies, a branch can change, the owner can change the content at any time so better be sure to trust whoever you take a fork from, they can add some code to search credentials and send them to some endpoint, modify other dependencies etc.

I would strongly recommend to think twice before putting stuff like that in a composer.json that can end in production, and even in a dev/local machine it's a risk to consider.

Secondly, as soon as the namespace is not `pdepend` or `phpmd`, it's out of out team responsibility and no warranty can be provided by our team on those repositories.

Last, branch are by nature not meant to live forever, one should not assume it would be permanent nor rely on it.

If you are on Symfony 6, please just lock your PDepend version until we'll provide the proper fix:

```shell
composer require pdepend/pdepend:~2.15 --dev
```

**Comment by kylekatarnls** [comment]
It's now fixed in master branch:

```
composer require "pdepend/pdepend:dev-master as 2.16.1" --dev
```

It will soon be released.
