### ISSUE TITLE
Broken Interface Type for Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder

### ISSUE THREAD

**Issue by jleonardolemos** [pdepend/pdepend#698]
- PHP Depend version: 2.16.0
- PHP Version: 8.3.0
- Installation type: composer
- Operating Docker image "php:8.3-fpm-alpine"

### Current Behavior
After upgrade to PHP 8.3 this error is happening when i execute phpmd
```
> vendor/bin/phpcs --standard=phpcs.xml --colors
> ./vendor/bin/phpmd src ansi ./phpmd.xml
PHP Fatal error:  Declaration of PDepend\DependencyInjection\Configuration::getConfigTreeBuilder() must be compatible with Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder(): Symfony\Component\Config\Definition\Builder\TreeBuilder in /var/www/audit-sdk/vendor/pdepend/pdepend/src/main/php/PDepend/DependencyInjection/Configuration.php on line 77

Fatal error: Declaration of PDepend\DependencyInjection\Configuration::getConfigTreeBuilder() must be compatible with Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder(): Symfony\Component\Config\Definition\Builder\TreeBuilder in /var/www/audit-sdk/vendor/pdepend/pdepend/src/main/php/PDepend/DependencyInjection/Configuration.php on line 77
```

### Expected Behavior
Running without erros

### Steps To Reproduce:
Just try with the latest symfony/config version.

### Extra:
The interface was changed in version 7.0 of `Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder`.
I was able to fix just typing the return type for `PDepend\DependencyInjection\Configuration::getConfigTreeBuilder`
Another workaround at my side would be to freeze the version in the composer.json file like that: "symfony/config": "^6.0"

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by AJenbo** [comment]
https://github.com/pdepend/pdepend/issues/695

**Comment by AJenbo** [comment]
Symfony 7 support implemented via https://github.com/pdepend/pdepend/pull/699
