### ISSUE TITLE
Implement code duplications

### ISSUE THREAD

**Issue by manuelpichler** [pdepend/pdepend#70]

**Comment by AJenbo** [comment]
Good idea, but with out a bit more of a description I think this issue isn't to useful. There are also other views that could be equally interesting to implement. Maybe instead we could make a list. Or have more fleshed out issues for each.

**Comment by ravage84** [comment]
There are other tools for that, such as the (nowadays deprecated) [PHPCPD](https://github.com/sebastianbergmann/phpcpd). Also IDEs like PhpStorm provide better code insight features today.
