### ISSUE TITLE
Use file-level class-annotation for classes

### ISSUE THREAD

**Issue by manuelpichler** [pdepend/pdepend#71]

**Comment by AJenbo** [comment]
I'm not sure I see the rational for this, it would be an easy change so if someone can add a good explanation to the issue I can maybe apply it to the code base. But for now I will close the issue.

**Comment by ravage84** [comment]
I can only assume but probably [annotations like the ones provided by PHPMD](https://phpmd.org/documentation/suppress-warnings.html) are meant.
