### ISSUE TITLE
Add support for property-accessor detection

### ISSUE THREAD

**Issue by manuelpichler** [pdepend/pdepend#76]

**Comment by AJenbo** [comment]
If by property-accessor we are refering to something like https://symfony.com/doc/current/components/property_access.html then I think this is non-trivial and the benefits of having it is also not directly clear. Closing for now.

**Comment by ravage84** [comment]
The PHP language has evolved quite a bit in the last 10+ years. As of PHP 7.1.0, we have [property visibility](https://www.php.net/manual/en/language.oop5.visibility.php).

And I only assume that [PHP Depend supports all of that](https://github.com/pdepend/pdepend/blob/master/CHANGELOG.md#pdepend-280-20200525), already. If something is missing, we can create a new issue for that.
