### ISSUE TITLE
FIlter pattern exclude regression

### ISSUE THREAD

**Issue by AJenbo** [pdepend/pdepend#766]
In PHPMD we have the following exclude pattern as part of the tests: `ccn_,npath_,parse_error`. This is to filter out `source_with_parse_error.php` which is a test case for a parsing error. If the filter does not work the `PHPMD\TextUI\CommandTest::testWithFilter` test will fail.

Since https://github.com/pdepend/pdepend/pull/721 this filter no longer works unless we change the pattern to `*ccn_,*npath_,*parse_error` which is probably not the intention, or at least it would probably catch a few people by surprise.

This is the new line:
https://github.com/pdepend/pdepend/blob/e2651e950b88e76edf621de41b5d2cc31c5e261c/src/main/php/PDepend/Input/ExcludePathFilter.php#L76

Possibly we can just remove `^`, or we need to revert back to having two patterns?

**Comment by kylekatarnls** [comment]
Hum, that was actually the intent of #721 to make "foo" to exclude "*/foo/*", "foo/*" or "*/foo" but not "*/foobar/*" nor "*/barfoo/*".

**Comment by kylekatarnls** [comment]
The thing is that it's easy to add a `*` and get what you need, but on the other side if we allow anything based on just `str_contains` then there is no way to actually exclude for instance `Controller.php` without excluding all `*Controller.php`.

**Comment by AJenbo** [comment]
Fair enough, I'll just update phpmd then, a little ironic maybe :)

**Comment by kylekatarnls** [comment]
BTW it's already released and no complain so far 🤷

**Comment by AJenbo** [comment]
> BTW it's already released and no complain so far 🤷

It was merged on Mar 20th, but the latest release is Dec 17. So it hasn't actually been released.

**Comment by kylekatarnls** [comment]
Ah true.

**Comment by AJenbo** [comment]
@kylekatarnls By the way did you see the poll on Gitter regarding what code style to adopt?
