### ISSUE TITLE
Dependencies on the class (and maybe even on the method) level in XML

### ISSUE THREAD

**Issue by sebastianbergmann** [pdepend/pdepend#89]
PHP_Depend currently only reports dependencies on the package level in the logfile generated by the `--jdepend-xml` option:

    <Package name="bankaccount\framework\http">
      
      <DependsUpon>
        <Package></Package>
        <Package>bankaccount\framework</Package>
      </DependsUpon>
      <UsedBy>
        <Package>bankaccount\controller</Package>
        <Package>bankaccount\framework</Package>
        <Package>bankaccount\framework\controller</Package>
        <Package>bankaccount\framework\factory</Package>
        <Package>bankaccount\framework\router</Package>
        <Package>bankaccount\framework\view</Package>
      </UsedBy>
    </Package>

It would be nice (and should not break compatibility with JDepend XML as it just adds additional elements) if that XML logfile would also report dependency information on the class (and maybe even on the method) level.

**Comment by manuelpichler** [comment]
A class based dependency report exists since commit c9f71cf73c7ea7cd211de652d760100f500f8ea1
